// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
	otps "sdk/otps"
	policies "sdk/policies"
	quotes "sdk/quotes"
)

type Client struct {
	Quotes   *quotes.Client
	Policies *policies.Client
	OtPs     *otps.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Quotes:   quotes.NewClient(options),
		Policies: policies.NewClient(options),
		OtPs:     otps.NewClient(options),
		options:  options,
		baseURL:  options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
