// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	internal "github.com/YasminaAI/motor-go-sdk/internal"
	big "math/big"
)

var (
	postIssueOtpRequestFieldEmail            = big.NewInt(1 << 0)
	postIssueOtpRequestFieldPhone            = big.NewInt(1 << 1)
	postIssueOtpRequestFieldOwnerID          = big.NewInt(1 << 2)
	postIssueOtpRequestFieldQuoteRequestID   = big.NewInt(1 << 3)
	postIssueOtpRequestFieldQuoteReferenceID = big.NewInt(1 << 4)
	postIssueOtpRequestFieldQuotePriceID     = big.NewInt(1 << 5)
)

type PostIssueOtpRequest struct {
	// Email address of the car owner
	Email string `json:"email" url:"-"`
	// Phone number starting with 05 and containing 10 digits
	Phone string `json:"phone" url:"-"`
	// National ID or Iqama ID of the car owner (10 digits)
	OwnerID string `json:"owner_id" url:"-"`
	// ID of the car quote request
	QuoteRequestID int `json:"quote_request_id" url:"-"`
	// Unique identifier for the quote reference ID (coming from POST /quote-requests)
	QuoteReferenceID string `json:"quote_reference_id" url:"-"`
	// Unique identifier for the quote price ID that exists inside a quote item (coming from POST /quote-requests)
	QuotePriceID string `json:"quote_price_id" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostIssueOtpRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostIssueOtpRequest) SetEmail(email string) {
	p.Email = email
	p.require(postIssueOtpRequestFieldEmail)
}

// SetPhone sets the Phone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostIssueOtpRequest) SetPhone(phone string) {
	p.Phone = phone
	p.require(postIssueOtpRequestFieldPhone)
}

// SetOwnerID sets the OwnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostIssueOtpRequest) SetOwnerID(ownerID string) {
	p.OwnerID = ownerID
	p.require(postIssueOtpRequestFieldOwnerID)
}

// SetQuoteRequestID sets the QuoteRequestID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostIssueOtpRequest) SetQuoteRequestID(quoteRequestID int) {
	p.QuoteRequestID = quoteRequestID
	p.require(postIssueOtpRequestFieldQuoteRequestID)
}

// SetQuoteReferenceID sets the QuoteReferenceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostIssueOtpRequest) SetQuoteReferenceID(quoteReferenceID string) {
	p.QuoteReferenceID = quoteReferenceID
	p.require(postIssueOtpRequestFieldQuoteReferenceID)
}

// SetQuotePriceID sets the QuotePriceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostIssueOtpRequest) SetQuotePriceID(quotePriceID string) {
	p.QuotePriceID = quotePriceID
	p.require(postIssueOtpRequestFieldQuotePriceID)
}

func (p *PostIssueOtpRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler PostIssueOtpRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = PostIssueOtpRequest(body)
	return nil
}

func (p *PostIssueOtpRequest) MarshalJSON() ([]byte, error) {
	type embed PostIssueOtpRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	postQuoteOtpRequestFieldEmail   = big.NewInt(1 << 0)
	postQuoteOtpRequestFieldPhone   = big.NewInt(1 << 1)
	postQuoteOtpRequestFieldOwnerID = big.NewInt(1 << 2)
)

type PostQuoteOtpRequest struct {
	// Email address of the car owner
	Email string `json:"email" url:"-"`
	// Phone number starting with 05 and containing 10 digits
	Phone string `json:"phone" url:"-"`
	// National ID or Iqama ID of the car owner (10 digits)
	OwnerID string `json:"owner_id" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostQuoteOtpRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteOtpRequest) SetEmail(email string) {
	p.Email = email
	p.require(postQuoteOtpRequestFieldEmail)
}

// SetPhone sets the Phone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteOtpRequest) SetPhone(phone string) {
	p.Phone = phone
	p.require(postQuoteOtpRequestFieldPhone)
}

// SetOwnerID sets the OwnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteOtpRequest) SetOwnerID(ownerID string) {
	p.OwnerID = ownerID
	p.require(postQuoteOtpRequestFieldOwnerID)
}

func (p *PostQuoteOtpRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler PostQuoteOtpRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = PostQuoteOtpRequest(body)
	return nil
}

func (p *PostQuoteOtpRequest) MarshalJSON() ([]byte, error) {
	type embed PostQuoteOtpRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}
