// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersPostIssueOtpRequest(t *testing.T) {
	t.Run("SetEmail", func(t *testing.T) {
		obj := &PostIssueOtpRequest{}
		var fernTestValueEmail string
		obj.SetEmail(fernTestValueEmail)
		assert.Equal(t, fernTestValueEmail, obj.Email)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPhone", func(t *testing.T) {
		obj := &PostIssueOtpRequest{}
		var fernTestValuePhone string
		obj.SetPhone(fernTestValuePhone)
		assert.Equal(t, fernTestValuePhone, obj.Phone)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOwnerID", func(t *testing.T) {
		obj := &PostIssueOtpRequest{}
		var fernTestValueOwnerID string
		obj.SetOwnerID(fernTestValueOwnerID)
		assert.Equal(t, fernTestValueOwnerID, obj.OwnerID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetQuoteRequestID", func(t *testing.T) {
		obj := &PostIssueOtpRequest{}
		var fernTestValueQuoteRequestID int
		obj.SetQuoteRequestID(fernTestValueQuoteRequestID)
		assert.Equal(t, fernTestValueQuoteRequestID, obj.QuoteRequestID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetQuoteReferenceID", func(t *testing.T) {
		obj := &PostIssueOtpRequest{}
		var fernTestValueQuoteReferenceID string
		obj.SetQuoteReferenceID(fernTestValueQuoteReferenceID)
		assert.Equal(t, fernTestValueQuoteReferenceID, obj.QuoteReferenceID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetQuotePriceID", func(t *testing.T) {
		obj := &PostIssueOtpRequest{}
		var fernTestValueQuotePriceID string
		obj.SetQuotePriceID(fernTestValueQuotePriceID)
		assert.Equal(t, fernTestValueQuotePriceID, obj.QuotePriceID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitPostIssueOtpRequest(t *testing.T) {
	t.Run("SetEmail_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PostIssueOtpRequest{}
		var fernTestValueEmail string

		// Act
		obj.SetEmail(fernTestValueEmail)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPhone_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PostIssueOtpRequest{}
		var fernTestValuePhone string

		// Act
		obj.SetPhone(fernTestValuePhone)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOwnerID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PostIssueOtpRequest{}
		var fernTestValueOwnerID string

		// Act
		obj.SetOwnerID(fernTestValueOwnerID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetQuoteRequestID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PostIssueOtpRequest{}
		var fernTestValueQuoteRequestID int

		// Act
		obj.SetQuoteRequestID(fernTestValueQuoteRequestID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetQuoteReferenceID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PostIssueOtpRequest{}
		var fernTestValueQuoteReferenceID string

		// Act
		obj.SetQuoteReferenceID(fernTestValueQuoteReferenceID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetQuotePriceID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PostIssueOtpRequest{}
		var fernTestValueQuotePriceID string

		// Act
		obj.SetQuotePriceID(fernTestValueQuotePriceID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersPostQuoteOtpRequest(t *testing.T) {
	t.Run("SetEmail", func(t *testing.T) {
		obj := &PostQuoteOtpRequest{}
		var fernTestValueEmail string
		obj.SetEmail(fernTestValueEmail)
		assert.Equal(t, fernTestValueEmail, obj.Email)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPhone", func(t *testing.T) {
		obj := &PostQuoteOtpRequest{}
		var fernTestValuePhone string
		obj.SetPhone(fernTestValuePhone)
		assert.Equal(t, fernTestValuePhone, obj.Phone)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOwnerID", func(t *testing.T) {
		obj := &PostQuoteOtpRequest{}
		var fernTestValueOwnerID string
		obj.SetOwnerID(fernTestValueOwnerID)
		assert.Equal(t, fernTestValueOwnerID, obj.OwnerID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitPostQuoteOtpRequest(t *testing.T) {
	t.Run("SetEmail_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PostQuoteOtpRequest{}
		var fernTestValueEmail string

		// Act
		obj.SetEmail(fernTestValueEmail)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPhone_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PostQuoteOtpRequest{}
		var fernTestValuePhone string

		// Act
		obj.SetPhone(fernTestValuePhone)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOwnerID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PostQuoteOtpRequest{}
		var fernTestValueOwnerID string

		// Act
		obj.SetOwnerID(fernTestValueOwnerID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}
