// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersPostPoliciesRequest(t *testing.T) {
	t.Run("SetQuoteRequestID", func(t *testing.T) {
		obj := &PostPoliciesRequest{}
		var fernTestValueQuoteRequestID int
		obj.SetQuoteRequestID(fernTestValueQuoteRequestID)
		assert.Equal(t, fernTestValueQuoteRequestID, obj.QuoteRequestID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetQuoteReferenceID", func(t *testing.T) {
		obj := &PostPoliciesRequest{}
		var fernTestValueQuoteReferenceID string
		obj.SetQuoteReferenceID(fernTestValueQuoteReferenceID)
		assert.Equal(t, fernTestValueQuoteReferenceID, obj.QuoteReferenceID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetQuotePriceID", func(t *testing.T) {
		obj := &PostPoliciesRequest{}
		var fernTestValueQuotePriceID string
		obj.SetQuotePriceID(fernTestValueQuotePriceID)
		assert.Equal(t, fernTestValueQuotePriceID, obj.QuotePriceID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetBenefits", func(t *testing.T) {
		obj := &PostPoliciesRequest{}
		var fernTestValueBenefits []string
		obj.SetBenefits(fernTestValueBenefits)
		assert.Equal(t, fernTestValueBenefits, obj.Benefits)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExtraFields", func(t *testing.T) {
		obj := &PostPoliciesRequest{}
		var fernTestValueExtraFields map[string]any
		obj.SetExtraFields(fernTestValueExtraFields)
		assert.Equal(t, fernTestValueExtraFields, obj.ExtraFields)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitPostPoliciesRequest(t *testing.T) {
	t.Run("SetQuoteRequestID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PostPoliciesRequest{}
		var fernTestValueQuoteRequestID int

		// Act
		obj.SetQuoteRequestID(fernTestValueQuoteRequestID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetQuoteReferenceID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PostPoliciesRequest{}
		var fernTestValueQuoteReferenceID string

		// Act
		obj.SetQuoteReferenceID(fernTestValueQuoteReferenceID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetQuotePriceID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PostPoliciesRequest{}
		var fernTestValueQuotePriceID string

		// Act
		obj.SetQuotePriceID(fernTestValueQuotePriceID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetBenefits_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PostPoliciesRequest{}
		var fernTestValueBenefits []string

		// Act
		obj.SetBenefits(fernTestValueBenefits)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExtraFields_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PostPoliciesRequest{}
		var fernTestValueExtraFields map[string]any

		// Act
		obj.SetExtraFields(fernTestValueExtraFields)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetPoliciesRequest(t *testing.T) {
	t.Run("SetQuoteRequestID", func(t *testing.T) {
		obj := &GetPoliciesRequest{}
		var fernTestValueQuoteRequestID *int
		obj.SetQuoteRequestID(fernTestValueQuoteRequestID)
		assert.Equal(t, fernTestValueQuoteRequestID, obj.QuoteRequestID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetQuotePriceID", func(t *testing.T) {
		obj := &GetPoliciesRequest{}
		var fernTestValueQuotePriceID *string
		obj.SetQuotePriceID(fernTestValueQuotePriceID)
		assert.Equal(t, fernTestValueQuotePriceID, obj.QuotePriceID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProviderPolicyID", func(t *testing.T) {
		obj := &GetPoliciesRequest{}
		var fernTestValueProviderPolicyID *int
		obj.SetProviderPolicyID(fernTestValueProviderPolicyID)
		assert.Equal(t, fernTestValueProviderPolicyID, obj.ProviderPolicyID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCarSequenceNumber", func(t *testing.T) {
		obj := &GetPoliciesRequest{}
		var fernTestValueCarSequenceNumber *string
		obj.SetCarSequenceNumber(fernTestValueCarSequenceNumber)
		assert.Equal(t, fernTestValueCarSequenceNumber, obj.CarSequenceNumber)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNewOwnerID", func(t *testing.T) {
		obj := &GetPoliciesRequest{}
		var fernTestValueNewOwnerID *string
		obj.SetNewOwnerID(fernTestValueNewOwnerID)
		assert.Equal(t, fernTestValueNewOwnerID, obj.NewOwnerID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPreviousOwnerID", func(t *testing.T) {
		obj := &GetPoliciesRequest{}
		var fernTestValuePreviousOwnerID *string
		obj.SetPreviousOwnerID(fernTestValuePreviousOwnerID)
		assert.Equal(t, fernTestValuePreviousOwnerID, obj.PreviousOwnerID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStatus", func(t *testing.T) {
		obj := &GetPoliciesRequest{}
		var fernTestValueStatus *int
		obj.SetStatus(fernTestValueStatus)
		assert.Equal(t, fernTestValueStatus, obj.Status)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMinPrice", func(t *testing.T) {
		obj := &GetPoliciesRequest{}
		var fernTestValueMinPrice *float64
		obj.SetMinPrice(fernTestValueMinPrice)
		assert.Equal(t, fernTestValueMinPrice, obj.MinPrice)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMaxPrice", func(t *testing.T) {
		obj := &GetPoliciesRequest{}
		var fernTestValueMaxPrice *float64
		obj.SetMaxPrice(fernTestValueMaxPrice)
		assert.Equal(t, fernTestValueMaxPrice, obj.MaxPrice)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPerPage", func(t *testing.T) {
		obj := &GetPoliciesRequest{}
		var fernTestValuePerPage *int
		obj.SetPerPage(fernTestValuePerPage)
		assert.Equal(t, fernTestValuePerPage, obj.PerPage)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetPoliciesRequest(t *testing.T) {
	t.Run("SetQuoteRequestID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetPoliciesRequest{}
		var fernTestValueQuoteRequestID *int

		// Act
		obj.SetQuoteRequestID(fernTestValueQuoteRequestID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetQuotePriceID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetPoliciesRequest{}
		var fernTestValueQuotePriceID *string

		// Act
		obj.SetQuotePriceID(fernTestValueQuotePriceID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProviderPolicyID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetPoliciesRequest{}
		var fernTestValueProviderPolicyID *int

		// Act
		obj.SetProviderPolicyID(fernTestValueProviderPolicyID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCarSequenceNumber_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetPoliciesRequest{}
		var fernTestValueCarSequenceNumber *string

		// Act
		obj.SetCarSequenceNumber(fernTestValueCarSequenceNumber)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNewOwnerID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetPoliciesRequest{}
		var fernTestValueNewOwnerID *string

		// Act
		obj.SetNewOwnerID(fernTestValueNewOwnerID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPreviousOwnerID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetPoliciesRequest{}
		var fernTestValuePreviousOwnerID *string

		// Act
		obj.SetPreviousOwnerID(fernTestValuePreviousOwnerID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetPoliciesRequest{}
		var fernTestValueStatus *int

		// Act
		obj.SetStatus(fernTestValueStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMinPrice_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetPoliciesRequest{}
		var fernTestValueMinPrice *float64

		// Act
		obj.SetMinPrice(fernTestValueMinPrice)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMaxPrice_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetPoliciesRequest{}
		var fernTestValueMaxPrice *float64

		// Act
		obj.SetMaxPrice(fernTestValueMaxPrice)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPerPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetPoliciesRequest{}
		var fernTestValuePerPage *int

		// Act
		obj.SetPerPage(fernTestValuePerPage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetPoliciesCarPolicyRequest(t *testing.T) {
	t.Run("SetCarPolicy", func(t *testing.T) {
		obj := &GetPoliciesCarPolicyRequest{}
		var fernTestValueCarPolicy int
		obj.SetCarPolicy(fernTestValueCarPolicy)
		assert.Equal(t, fernTestValueCarPolicy, obj.CarPolicy)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetPoliciesCarPolicyRequest(t *testing.T) {
	t.Run("SetCarPolicy_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetPoliciesCarPolicyRequest{}
		var fernTestValueCarPolicy int

		// Act
		obj.SetCarPolicy(fernTestValueCarPolicy)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersPolicy(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &Policy{}
		var fernTestValueID *int
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMetaData", func(t *testing.T) {
		obj := &Policy{}
		var fernTestValueMetaData map[string]any
		obj.SetMetaData(fernTestValueMetaData)
		assert.Equal(t, fernTestValueMetaData, obj.MetaData)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStartDate", func(t *testing.T) {
		obj := &Policy{}
		var fernTestValueStartDate *string
		obj.SetStartDate(fernTestValueStartDate)
		assert.Equal(t, fernTestValueStartDate, obj.StartDate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProviderPolicyID", func(t *testing.T) {
		obj := &Policy{}
		var fernTestValueProviderPolicyID *int
		obj.SetProviderPolicyID(fernTestValueProviderPolicyID)
		assert.Equal(t, fernTestValueProviderPolicyID, obj.ProviderPolicyID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProviderPolicy", func(t *testing.T) {
		obj := &Policy{}
		var fernTestValueProviderPolicy *string
		obj.SetProviderPolicy(fernTestValueProviderPolicy)
		assert.Equal(t, fernTestValueProviderPolicy, obj.ProviderPolicy)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOrderStatus", func(t *testing.T) {
		obj := &Policy{}
		var fernTestValueOrderStatus *int
		obj.SetOrderStatus(fernTestValueOrderStatus)
		assert.Equal(t, fernTestValueOrderStatus, obj.OrderStatus)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetApprovalStatus", func(t *testing.T) {
		obj := &Policy{}
		var fernTestValueApprovalStatus *int
		obj.SetApprovalStatus(fernTestValueApprovalStatus)
		assert.Equal(t, fernTestValueApprovalStatus, obj.ApprovalStatus)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEndDate", func(t *testing.T) {
		obj := &Policy{}
		var fernTestValueEndDate *string
		obj.SetEndDate(fernTestValueEndDate)
		assert.Equal(t, fernTestValueEndDate, obj.EndDate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIsClaimed", func(t *testing.T) {
		obj := &Policy{}
		var fernTestValueIsClaimed *bool
		obj.SetIsClaimed(fernTestValueIsClaimed)
		assert.Equal(t, fernTestValueIsClaimed, obj.IsClaimed)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &Policy{}
		var fernTestValueCreatedAt *string
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUpdatedAt", func(t *testing.T) {
		obj := &Policy{}
		var fernTestValueUpdatedAt *string
		obj.SetUpdatedAt(fernTestValueUpdatedAt)
		assert.Equal(t, fernTestValueUpdatedAt, obj.UpdatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetClientID", func(t *testing.T) {
		obj := &Policy{}
		var fernTestValueClientID *string
		obj.SetClientID(fernTestValueClientID)
		assert.Equal(t, fernTestValueClientID, obj.ClientID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCanceledAt", func(t *testing.T) {
		obj := &Policy{}
		var fernTestValueCanceledAt *string
		obj.SetCanceledAt(fernTestValueCanceledAt)
		assert.Equal(t, fernTestValueCanceledAt, obj.CanceledAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetInvoice", func(t *testing.T) {
		obj := &Policy{}
		var fernTestValueInvoice *string
		obj.SetInvoice(fernTestValueInvoice)
		assert.Equal(t, fernTestValueInvoice, obj.Invoice)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCancellationDocument", func(t *testing.T) {
		obj := &Policy{}
		var fernTestValueCancellationDocument *string
		obj.SetCancellationDocument(fernTestValueCancellationDocument)
		assert.Equal(t, fernTestValueCancellationDocument, obj.CancellationDocument)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersPolicy(t *testing.T) {
	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var expected *int
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		obj.ID = nil

		// Act & Assert
		assert.Nil(t, obj.GetID(), "getter should return nil when property is nil")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Policy
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetMetaData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var expected map[string]any
		obj.MetaData = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMetaData(), "getter should return the property value")
	})

	t.Run("GetMetaData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		obj.MetaData = nil

		// Act & Assert
		assert.Nil(t, obj.GetMetaData(), "getter should return nil when property is nil")
	})

	t.Run("GetMetaData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Policy
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMetaData() // Should return zero value
	})

	t.Run("GetStartDate", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var expected *string
		obj.StartDate = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStartDate(), "getter should return the property value")
	})

	t.Run("GetStartDate_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		obj.StartDate = nil

		// Act & Assert
		assert.Nil(t, obj.GetStartDate(), "getter should return nil when property is nil")
	})

	t.Run("GetStartDate_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Policy
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStartDate() // Should return zero value
	})

	t.Run("GetProviderPolicyID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var expected *int
		obj.ProviderPolicyID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetProviderPolicyID(), "getter should return the property value")
	})

	t.Run("GetProviderPolicyID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		obj.ProviderPolicyID = nil

		// Act & Assert
		assert.Nil(t, obj.GetProviderPolicyID(), "getter should return nil when property is nil")
	})

	t.Run("GetProviderPolicyID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Policy
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetProviderPolicyID() // Should return zero value
	})

	t.Run("GetProviderPolicy", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var expected *string
		obj.ProviderPolicy = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetProviderPolicy(), "getter should return the property value")
	})

	t.Run("GetProviderPolicy_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		obj.ProviderPolicy = nil

		// Act & Assert
		assert.Nil(t, obj.GetProviderPolicy(), "getter should return nil when property is nil")
	})

	t.Run("GetProviderPolicy_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Policy
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetProviderPolicy() // Should return zero value
	})

	t.Run("GetOrderStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var expected *int
		obj.OrderStatus = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOrderStatus(), "getter should return the property value")
	})

	t.Run("GetOrderStatus_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		obj.OrderStatus = nil

		// Act & Assert
		assert.Nil(t, obj.GetOrderStatus(), "getter should return nil when property is nil")
	})

	t.Run("GetOrderStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Policy
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOrderStatus() // Should return zero value
	})

	t.Run("GetApprovalStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var expected *int
		obj.ApprovalStatus = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetApprovalStatus(), "getter should return the property value")
	})

	t.Run("GetApprovalStatus_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		obj.ApprovalStatus = nil

		// Act & Assert
		assert.Nil(t, obj.GetApprovalStatus(), "getter should return nil when property is nil")
	})

	t.Run("GetApprovalStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Policy
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetApprovalStatus() // Should return zero value
	})

	t.Run("GetEndDate", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var expected *string
		obj.EndDate = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEndDate(), "getter should return the property value")
	})

	t.Run("GetEndDate_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		obj.EndDate = nil

		// Act & Assert
		assert.Nil(t, obj.GetEndDate(), "getter should return nil when property is nil")
	})

	t.Run("GetEndDate_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Policy
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEndDate() // Should return zero value
	})

	t.Run("GetIsClaimed", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var expected *bool
		obj.IsClaimed = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIsClaimed(), "getter should return the property value")
	})

	t.Run("GetIsClaimed_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		obj.IsClaimed = nil

		// Act & Assert
		assert.Nil(t, obj.GetIsClaimed(), "getter should return nil when property is nil")
	})

	t.Run("GetIsClaimed_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Policy
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIsClaimed() // Should return zero value
	})

	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var expected *string
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		obj.CreatedAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetCreatedAt(), "getter should return nil when property is nil")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Policy
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

	t.Run("GetUpdatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var expected *string
		obj.UpdatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUpdatedAt(), "getter should return the property value")
	})

	t.Run("GetUpdatedAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		obj.UpdatedAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetUpdatedAt(), "getter should return nil when property is nil")
	})

	t.Run("GetUpdatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Policy
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUpdatedAt() // Should return zero value
	})

	t.Run("GetClientID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var expected *string
		obj.ClientID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetClientID(), "getter should return the property value")
	})

	t.Run("GetClientID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		obj.ClientID = nil

		// Act & Assert
		assert.Nil(t, obj.GetClientID(), "getter should return nil when property is nil")
	})

	t.Run("GetClientID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Policy
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetClientID() // Should return zero value
	})

	t.Run("GetCanceledAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var expected *string
		obj.CanceledAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCanceledAt(), "getter should return the property value")
	})

	t.Run("GetCanceledAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		obj.CanceledAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetCanceledAt(), "getter should return nil when property is nil")
	})

	t.Run("GetCanceledAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Policy
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCanceledAt() // Should return zero value
	})

	t.Run("GetInvoice", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var expected *string
		obj.Invoice = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetInvoice(), "getter should return the property value")
	})

	t.Run("GetInvoice_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		obj.Invoice = nil

		// Act & Assert
		assert.Nil(t, obj.GetInvoice(), "getter should return nil when property is nil")
	})

	t.Run("GetInvoice_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Policy
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetInvoice() // Should return zero value
	})

	t.Run("GetCancellationDocument", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var expected *string
		obj.CancellationDocument = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCancellationDocument(), "getter should return the property value")
	})

	t.Run("GetCancellationDocument_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		obj.CancellationDocument = nil

		// Act & Assert
		assert.Nil(t, obj.GetCancellationDocument(), "getter should return nil when property is nil")
	})

	t.Run("GetCancellationDocument_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Policy
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCancellationDocument() // Should return zero value
	})

}

func TestSettersMarkExplicitPolicy(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var fernTestValueID *int

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMetaData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var fernTestValueMetaData map[string]any

		// Act
		obj.SetMetaData(fernTestValueMetaData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStartDate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var fernTestValueStartDate *string

		// Act
		obj.SetStartDate(fernTestValueStartDate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProviderPolicyID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var fernTestValueProviderPolicyID *int

		// Act
		obj.SetProviderPolicyID(fernTestValueProviderPolicyID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProviderPolicy_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var fernTestValueProviderPolicy *string

		// Act
		obj.SetProviderPolicy(fernTestValueProviderPolicy)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOrderStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var fernTestValueOrderStatus *int

		// Act
		obj.SetOrderStatus(fernTestValueOrderStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetApprovalStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var fernTestValueApprovalStatus *int

		// Act
		obj.SetApprovalStatus(fernTestValueApprovalStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEndDate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var fernTestValueEndDate *string

		// Act
		obj.SetEndDate(fernTestValueEndDate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIsClaimed_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var fernTestValueIsClaimed *bool

		// Act
		obj.SetIsClaimed(fernTestValueIsClaimed)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var fernTestValueCreatedAt *string

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUpdatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var fernTestValueUpdatedAt *string

		// Act
		obj.SetUpdatedAt(fernTestValueUpdatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetClientID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var fernTestValueClientID *string

		// Act
		obj.SetClientID(fernTestValueClientID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCanceledAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var fernTestValueCanceledAt *string

		// Act
		obj.SetCanceledAt(fernTestValueCanceledAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetInvoice_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var fernTestValueInvoice *string

		// Act
		obj.SetInvoice(fernTestValueInvoice)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCancellationDocument_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}
		var fernTestValueCancellationDocument *string

		// Act
		obj.SetCancellationDocument(fernTestValueCancellationDocument)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingPolicy(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Policy{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled Policy
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj Policy
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj Policy
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringPolicy(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &Policy{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Policy
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesPolicy(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &Policy{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Policy
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
