// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "sdk/internal"
	time "time"
)

var (
	deleteQuoteRequestsIDRequestFieldID = big.NewInt(1 << 0)
)

type DeleteQuoteRequestsIDRequest struct {
	ID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteQuoteRequestsIDRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteQuoteRequestsIDRequest) SetID(id int) {
	d.ID = id
	d.require(deleteQuoteRequestsIDRequestFieldID)
}

var (
	postQuoteRequestsRequestFieldOwnerID             = big.NewInt(1 << 0)
	postQuoteRequestsRequestFieldEmail               = big.NewInt(1 << 1)
	postQuoteRequestsRequestFieldPhone               = big.NewInt(1 << 2)
	postQuoteRequestsRequestFieldBirthdate           = big.NewInt(1 << 3)
	postQuoteRequestsRequestFieldCarSequenceNumber   = big.NewInt(1 << 4)
	postQuoteRequestsRequestFieldIsOwnershipTransfer = big.NewInt(1 << 5)
	postQuoteRequestsRequestFieldCurrentCarOwnerID   = big.NewInt(1 << 6)
	postQuoteRequestsRequestFieldCarEstimatedCost    = big.NewInt(1 << 7)
	postQuoteRequestsRequestFieldCarModelYear        = big.NewInt(1 << 8)
	postQuoteRequestsRequestFieldStartDate           = big.NewInt(1 << 9)
	postQuoteRequestsRequestFieldDrivers             = big.NewInt(1 << 10)
)

type PostQuoteRequestsRequest struct {
	// Owner ID must be 10 digits starting with 1, 2, or 7
	OwnerID string `json:"owner_id" url:"-"`
	// Email address must be valid and belongs to the customer
	Email *string `json:"email,omitempty" url:"-"`
	// Phone number must start with 05 and be 10 digits
	Phone string `json:"phone" url:"-"`
	// Birthdate in YYYY-MM-DD format
	Birthdate time.Time `json:"birthdate" url:"-" format:"date"`
	// Car sequence number must be 8 or 9 digits
	CarSequenceNumber string `json:"car_sequence_number" url:"-"`
	// Indicates if the ownership is being transferred
	IsOwnershipTransfer *bool `json:"is_ownership_transfer,omitempty" url:"-"`
	// Required if is_ownership_transfer is true; 10 digits starting with 1,2,7
	CurrentCarOwnerID *string `json:"current_car_owner_id,omitempty" url:"-"`
	// Estimated cost of the car
	CarEstimatedCost float64 `json:"car_estimated_cost" url:"-"`
	// Car model year between 1950 and next year
	CarModelYear *int `json:"car_model_year,omitempty" url:"-"`
	// Desired policy start date in YYYY-MM-DD. Must be between tomorrow and 28 days from today (inclusive). The platform validates this range server-side.
	StartDate *time.Time `json:"start_date,omitempty" url:"-" format:"date"`
	// List of drivers for the vehicle. When provided, the sum of all driving_percentage values must equal 100, and the owner must be included among the drivers.
	Drivers []*PostQuoteRequestsRequestDriversItem `json:"drivers,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostQuoteRequestsRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetOwnerID sets the OwnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetOwnerID(ownerID string) {
	p.OwnerID = ownerID
	p.require(postQuoteRequestsRequestFieldOwnerID)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetEmail(email *string) {
	p.Email = email
	p.require(postQuoteRequestsRequestFieldEmail)
}

// SetPhone sets the Phone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetPhone(phone string) {
	p.Phone = phone
	p.require(postQuoteRequestsRequestFieldPhone)
}

// SetBirthdate sets the Birthdate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetBirthdate(birthdate time.Time) {
	p.Birthdate = birthdate
	p.require(postQuoteRequestsRequestFieldBirthdate)
}

// SetCarSequenceNumber sets the CarSequenceNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetCarSequenceNumber(carSequenceNumber string) {
	p.CarSequenceNumber = carSequenceNumber
	p.require(postQuoteRequestsRequestFieldCarSequenceNumber)
}

// SetIsOwnershipTransfer sets the IsOwnershipTransfer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetIsOwnershipTransfer(isOwnershipTransfer *bool) {
	p.IsOwnershipTransfer = isOwnershipTransfer
	p.require(postQuoteRequestsRequestFieldIsOwnershipTransfer)
}

// SetCurrentCarOwnerID sets the CurrentCarOwnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetCurrentCarOwnerID(currentCarOwnerID *string) {
	p.CurrentCarOwnerID = currentCarOwnerID
	p.require(postQuoteRequestsRequestFieldCurrentCarOwnerID)
}

// SetCarEstimatedCost sets the CarEstimatedCost field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetCarEstimatedCost(carEstimatedCost float64) {
	p.CarEstimatedCost = carEstimatedCost
	p.require(postQuoteRequestsRequestFieldCarEstimatedCost)
}

// SetCarModelYear sets the CarModelYear field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetCarModelYear(carModelYear *int) {
	p.CarModelYear = carModelYear
	p.require(postQuoteRequestsRequestFieldCarModelYear)
}

// SetStartDate sets the StartDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetStartDate(startDate *time.Time) {
	p.StartDate = startDate
	p.require(postQuoteRequestsRequestFieldStartDate)
}

// SetDrivers sets the Drivers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetDrivers(drivers []*PostQuoteRequestsRequestDriversItem) {
	p.Drivers = drivers
	p.require(postQuoteRequestsRequestFieldDrivers)
}

func (p *PostQuoteRequestsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler PostQuoteRequestsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = PostQuoteRequestsRequest(body)
	return nil
}

func (p *PostQuoteRequestsRequest) MarshalJSON() ([]byte, error) {
	type embed PostQuoteRequestsRequest
	var marshaler = struct {
		embed
		Birthdate *internal.Date `json:"birthdate"`
		StartDate *internal.Date `json:"start_date,omitempty"`
	}{
		embed:     embed(*p),
		Birthdate: internal.NewDate(p.Birthdate),
		StartDate: internal.NewOptionalDate(p.StartDate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getQuoteRequestsIDRequestFieldID = big.NewInt(1 << 0)
)

type GetQuoteRequestsIDRequest struct {
	ID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetQuoteRequestsIDRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsIDRequest) SetID(id int) {
	g.ID = id
	g.require(getQuoteRequestsIDRequestFieldID)
}

var (
	benefitFieldQuoteBenefitID = big.NewInt(1 << 0)
	benefitFieldID             = big.NewInt(1 << 1)
	benefitFieldName           = big.NewInt(1 << 2)
	benefitFieldAmount         = big.NewInt(1 << 3)
	benefitFieldVat            = big.NewInt(1 << 4)
	benefitFieldURL            = big.NewInt(1 << 5)
)

type Benefit struct {
	QuoteBenefitID *string  `json:"quote_benefit_id,omitempty" url:"quote_benefit_id,omitempty"`
	ID             *string  `json:"id,omitempty" url:"id,omitempty"`
	Name           *string  `json:"name,omitempty" url:"name,omitempty"`
	Amount         *float64 `json:"amount,omitempty" url:"amount,omitempty"`
	Vat            *float64 `json:"vat,omitempty" url:"vat,omitempty"`
	URL            *string  `json:"url,omitempty" url:"url,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *Benefit) GetQuoteBenefitID() *string {
	if b == nil {
		return nil
	}
	return b.QuoteBenefitID
}

func (b *Benefit) GetID() *string {
	if b == nil {
		return nil
	}
	return b.ID
}

func (b *Benefit) GetName() *string {
	if b == nil {
		return nil
	}
	return b.Name
}

func (b *Benefit) GetAmount() *float64 {
	if b == nil {
		return nil
	}
	return b.Amount
}

func (b *Benefit) GetVat() *float64 {
	if b == nil {
		return nil
	}
	return b.Vat
}

func (b *Benefit) GetURL() *string {
	if b == nil {
		return nil
	}
	return b.URL
}

func (b *Benefit) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *Benefit) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetQuoteBenefitID sets the QuoteBenefitID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Benefit) SetQuoteBenefitID(quoteBenefitID *string) {
	b.QuoteBenefitID = quoteBenefitID
	b.require(benefitFieldQuoteBenefitID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Benefit) SetID(id *string) {
	b.ID = id
	b.require(benefitFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Benefit) SetName(name *string) {
	b.Name = name
	b.require(benefitFieldName)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Benefit) SetAmount(amount *float64) {
	b.Amount = amount
	b.require(benefitFieldAmount)
}

// SetVat sets the Vat field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Benefit) SetVat(vat *float64) {
	b.Vat = vat
	b.require(benefitFieldVat)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Benefit) SetURL(url *string) {
	b.URL = url
	b.require(benefitFieldURL)
}

func (b *Benefit) UnmarshalJSON(data []byte) error {
	type unmarshaler Benefit
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = Benefit(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *Benefit) MarshalJSON() ([]byte, error) {
	type embed Benefit
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *Benefit) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	quotePriceFieldQuotePriceID  = big.NewInt(1 << 0)
	quotePriceFieldDeductible    = big.NewInt(1 << 1)
	quotePriceFieldSubtotal      = big.NewInt(1 << 2)
	quotePriceFieldVatPercentage = big.NewInt(1 << 3)
	quotePriceFieldVat           = big.NewInt(1 << 4)
	quotePriceFieldTotal         = big.NewInt(1 << 5)
)

type QuotePrice struct {
	QuotePriceID  *string  `json:"quote_price_id,omitempty" url:"quote_price_id,omitempty"`
	Deductible    *float64 `json:"deductible,omitempty" url:"deductible,omitempty"`
	Subtotal      *float64 `json:"subtotal,omitempty" url:"subtotal,omitempty"`
	VatPercentage *float64 `json:"vat_percentage,omitempty" url:"vat_percentage,omitempty"`
	Vat           *float64 `json:"vat,omitempty" url:"vat,omitempty"`
	Total         *float64 `json:"total,omitempty" url:"total,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (q *QuotePrice) GetQuotePriceID() *string {
	if q == nil {
		return nil
	}
	return q.QuotePriceID
}

func (q *QuotePrice) GetDeductible() *float64 {
	if q == nil {
		return nil
	}
	return q.Deductible
}

func (q *QuotePrice) GetSubtotal() *float64 {
	if q == nil {
		return nil
	}
	return q.Subtotal
}

func (q *QuotePrice) GetVatPercentage() *float64 {
	if q == nil {
		return nil
	}
	return q.VatPercentage
}

func (q *QuotePrice) GetVat() *float64 {
	if q == nil {
		return nil
	}
	return q.Vat
}

func (q *QuotePrice) GetTotal() *float64 {
	if q == nil {
		return nil
	}
	return q.Total
}

func (q *QuotePrice) GetExtraProperties() map[string]interface{} {
	if q == nil {
		return nil
	}
	return q.extraProperties
}

func (q *QuotePrice) require(field *big.Int) {
	if q.explicitFields == nil {
		q.explicitFields = big.NewInt(0)
	}
	q.explicitFields.Or(q.explicitFields, field)
}

// SetQuotePriceID sets the QuotePriceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuotePrice) SetQuotePriceID(quotePriceID *string) {
	q.QuotePriceID = quotePriceID
	q.require(quotePriceFieldQuotePriceID)
}

// SetDeductible sets the Deductible field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuotePrice) SetDeductible(deductible *float64) {
	q.Deductible = deductible
	q.require(quotePriceFieldDeductible)
}

// SetSubtotal sets the Subtotal field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuotePrice) SetSubtotal(subtotal *float64) {
	q.Subtotal = subtotal
	q.require(quotePriceFieldSubtotal)
}

// SetVatPercentage sets the VatPercentage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuotePrice) SetVatPercentage(vatPercentage *float64) {
	q.VatPercentage = vatPercentage
	q.require(quotePriceFieldVatPercentage)
}

// SetVat sets the Vat field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuotePrice) SetVat(vat *float64) {
	q.Vat = vat
	q.require(quotePriceFieldVat)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuotePrice) SetTotal(total *float64) {
	q.Total = total
	q.require(quotePriceFieldTotal)
}

func (q *QuotePrice) UnmarshalJSON(data []byte) error {
	type unmarshaler QuotePrice
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*q = QuotePrice(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.extraProperties = extraProperties
	q.rawJSON = json.RawMessage(data)
	return nil
}

func (q *QuotePrice) MarshalJSON() ([]byte, error) {
	type embed QuotePrice
	var marshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (q *QuotePrice) String() string {
	if q == nil {
		return "<nil>"
	}
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}

var (
	quoteResponseFieldOwnerID             = big.NewInt(1 << 0)
	quoteResponseFieldPhone               = big.NewInt(1 << 1)
	quoteResponseFieldBirthdate           = big.NewInt(1 << 2)
	quoteResponseFieldCarSequenceNumber   = big.NewInt(1 << 3)
	quoteResponseFieldIsOwnershipTransfer = big.NewInt(1 << 4)
	quoteResponseFieldCarEstimatedCost    = big.NewInt(1 << 5)
	quoteResponseFieldCarModelYear        = big.NewInt(1 << 6)
	quoteResponseFieldStartDate           = big.NewInt(1 << 7)
	quoteResponseFieldDrivers             = big.NewInt(1 << 8)
	quoteResponseFieldQuotes              = big.NewInt(1 << 9)
	quoteResponseFieldClientID            = big.NewInt(1 << 10)
	quoteResponseFieldUpdatedAt           = big.NewInt(1 << 11)
	quoteResponseFieldCreatedAt           = big.NewInt(1 << 12)
	quoteResponseFieldID                  = big.NewInt(1 << 13)
)

type QuoteResponse struct {
	// The owner’s national ID or Iqama ID
	OwnerID *int `json:"owner_id,omitempty" url:"owner_id,omitempty"`
	// The owner's phone number
	Phone *string `json:"phone,omitempty" url:"phone,omitempty"`
	// The owner's birthdate. Hijri for Saudi nationals, Gregorian for others
	Birthdate *time.Time `json:"birthdate,omitempty" url:"birthdate,omitempty" format:"date"`
	// The car sequence number from 9 digits
	CarSequenceNumber *int `json:"car_sequence_number,omitempty" url:"car_sequence_number,omitempty"`
	// Whether it was a car transfer or not
	IsOwnershipTransfer *bool `json:"is_ownership_transfer,omitempty" url:"is_ownership_transfer,omitempty"`
	// The estimated cost of the car
	CarEstimatedCost *float64 `json:"car_estimated_cost,omitempty" url:"car_estimated_cost,omitempty"`
	// The car model year
	CarModelYear *int `json:"car_model_year,omitempty" url:"car_model_year,omitempty"`
	// Requested policy start date in YYYY-MM-DD. Returned if provided in the quote request.
	StartDate *time.Time `json:"start_date,omitempty" url:"start_date,omitempty" format:"date"`
	// List of drivers associated with this quote request. Returned if drivers were provided in the request.
	Drivers []*QuoteResponseDriversItem `json:"drivers,omitempty" url:"drivers,omitempty"`
	// An array representing each insurance company quote. Each item has the company name, the prices, and the benefits.
	Quotes []*QuoteResponseQuotesItem `json:"quotes,omitempty" url:"quotes,omitempty"`
	// Your own client ID
	ClientID *string `json:"client_id,omitempty" url:"client_id,omitempty"`
	// In case of an update on this quote, this date will change
	UpdatedAt *time.Time `json:"updated_at,omitempty" url:"updated_at,omitempty"`
	// When was the quote requested
	CreatedAt *time.Time `json:"created_at,omitempty" url:"created_at,omitempty"`
	// Yasmina ID for the quote. You can use it to delete items or showing it again to the customer
	ID *int `json:"id,omitempty" url:"id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (q *QuoteResponse) GetOwnerID() *int {
	if q == nil {
		return nil
	}
	return q.OwnerID
}

func (q *QuoteResponse) GetPhone() *string {
	if q == nil {
		return nil
	}
	return q.Phone
}

func (q *QuoteResponse) GetBirthdate() *time.Time {
	if q == nil {
		return nil
	}
	return q.Birthdate
}

func (q *QuoteResponse) GetCarSequenceNumber() *int {
	if q == nil {
		return nil
	}
	return q.CarSequenceNumber
}

func (q *QuoteResponse) GetIsOwnershipTransfer() *bool {
	if q == nil {
		return nil
	}
	return q.IsOwnershipTransfer
}

func (q *QuoteResponse) GetCarEstimatedCost() *float64 {
	if q == nil {
		return nil
	}
	return q.CarEstimatedCost
}

func (q *QuoteResponse) GetCarModelYear() *int {
	if q == nil {
		return nil
	}
	return q.CarModelYear
}

func (q *QuoteResponse) GetStartDate() *time.Time {
	if q == nil {
		return nil
	}
	return q.StartDate
}

func (q *QuoteResponse) GetDrivers() []*QuoteResponseDriversItem {
	if q == nil {
		return nil
	}
	return q.Drivers
}

func (q *QuoteResponse) GetQuotes() []*QuoteResponseQuotesItem {
	if q == nil {
		return nil
	}
	return q.Quotes
}

func (q *QuoteResponse) GetClientID() *string {
	if q == nil {
		return nil
	}
	return q.ClientID
}

func (q *QuoteResponse) GetUpdatedAt() *time.Time {
	if q == nil {
		return nil
	}
	return q.UpdatedAt
}

func (q *QuoteResponse) GetCreatedAt() *time.Time {
	if q == nil {
		return nil
	}
	return q.CreatedAt
}

func (q *QuoteResponse) GetID() *int {
	if q == nil {
		return nil
	}
	return q.ID
}

func (q *QuoteResponse) GetExtraProperties() map[string]interface{} {
	if q == nil {
		return nil
	}
	return q.extraProperties
}

func (q *QuoteResponse) require(field *big.Int) {
	if q.explicitFields == nil {
		q.explicitFields = big.NewInt(0)
	}
	q.explicitFields.Or(q.explicitFields, field)
}

// SetOwnerID sets the OwnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetOwnerID(ownerID *int) {
	q.OwnerID = ownerID
	q.require(quoteResponseFieldOwnerID)
}

// SetPhone sets the Phone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetPhone(phone *string) {
	q.Phone = phone
	q.require(quoteResponseFieldPhone)
}

// SetBirthdate sets the Birthdate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetBirthdate(birthdate *time.Time) {
	q.Birthdate = birthdate
	q.require(quoteResponseFieldBirthdate)
}

// SetCarSequenceNumber sets the CarSequenceNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetCarSequenceNumber(carSequenceNumber *int) {
	q.CarSequenceNumber = carSequenceNumber
	q.require(quoteResponseFieldCarSequenceNumber)
}

// SetIsOwnershipTransfer sets the IsOwnershipTransfer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetIsOwnershipTransfer(isOwnershipTransfer *bool) {
	q.IsOwnershipTransfer = isOwnershipTransfer
	q.require(quoteResponseFieldIsOwnershipTransfer)
}

// SetCarEstimatedCost sets the CarEstimatedCost field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetCarEstimatedCost(carEstimatedCost *float64) {
	q.CarEstimatedCost = carEstimatedCost
	q.require(quoteResponseFieldCarEstimatedCost)
}

// SetCarModelYear sets the CarModelYear field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetCarModelYear(carModelYear *int) {
	q.CarModelYear = carModelYear
	q.require(quoteResponseFieldCarModelYear)
}

// SetStartDate sets the StartDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetStartDate(startDate *time.Time) {
	q.StartDate = startDate
	q.require(quoteResponseFieldStartDate)
}

// SetDrivers sets the Drivers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetDrivers(drivers []*QuoteResponseDriversItem) {
	q.Drivers = drivers
	q.require(quoteResponseFieldDrivers)
}

// SetQuotes sets the Quotes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetQuotes(quotes []*QuoteResponseQuotesItem) {
	q.Quotes = quotes
	q.require(quoteResponseFieldQuotes)
}

// SetClientID sets the ClientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetClientID(clientID *string) {
	q.ClientID = clientID
	q.require(quoteResponseFieldClientID)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetUpdatedAt(updatedAt *time.Time) {
	q.UpdatedAt = updatedAt
	q.require(quoteResponseFieldUpdatedAt)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetCreatedAt(createdAt *time.Time) {
	q.CreatedAt = createdAt
	q.require(quoteResponseFieldCreatedAt)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetID(id *int) {
	q.ID = id
	q.require(quoteResponseFieldID)
}

func (q *QuoteResponse) UnmarshalJSON(data []byte) error {
	type embed QuoteResponse
	var unmarshaler = struct {
		embed
		Birthdate *internal.Date     `json:"birthdate,omitempty"`
		StartDate *internal.Date     `json:"start_date,omitempty"`
		UpdatedAt *internal.DateTime `json:"updated_at,omitempty"`
		CreatedAt *internal.DateTime `json:"created_at,omitempty"`
	}{
		embed: embed(*q),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*q = QuoteResponse(unmarshaler.embed)
	q.Birthdate = unmarshaler.Birthdate.TimePtr()
	q.StartDate = unmarshaler.StartDate.TimePtr()
	q.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()
	q.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.extraProperties = extraProperties
	q.rawJSON = json.RawMessage(data)
	return nil
}

func (q *QuoteResponse) MarshalJSON() ([]byte, error) {
	type embed QuoteResponse
	var marshaler = struct {
		embed
		Birthdate *internal.Date     `json:"birthdate,omitempty"`
		StartDate *internal.Date     `json:"start_date,omitempty"`
		UpdatedAt *internal.DateTime `json:"updated_at,omitempty"`
		CreatedAt *internal.DateTime `json:"created_at,omitempty"`
	}{
		embed:     embed(*q),
		Birthdate: internal.NewOptionalDate(q.Birthdate),
		StartDate: internal.NewOptionalDate(q.StartDate),
		UpdatedAt: internal.NewOptionalDateTime(q.UpdatedAt),
		CreatedAt: internal.NewOptionalDateTime(q.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (q *QuoteResponse) String() string {
	if q == nil {
		return "<nil>"
	}
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}

var (
	quoteResponseDriversItemFieldOwnerID           = big.NewInt(1 << 0)
	quoteResponseDriversItemFieldBirthdate         = big.NewInt(1 << 1)
	quoteResponseDriversItemFieldDrivingPercentage = big.NewInt(1 << 2)
)

type QuoteResponseDriversItem struct {
	// Driver's national ID (10 digits starting with 1, 2, or 7)
	OwnerID *string `json:"owner_id,omitempty" url:"owner_id,omitempty"`
	// Driver's birthdate in YYYY-MM-DD format
	Birthdate *time.Time `json:"birthdate,omitempty" url:"birthdate,omitempty" format:"date"`
	// Percentage of driving for this driver (25, 50, 75, or 100)
	DrivingPercentage *int `json:"driving_percentage,omitempty" url:"driving_percentage,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (q *QuoteResponseDriversItem) GetOwnerID() *string {
	if q == nil {
		return nil
	}
	return q.OwnerID
}

func (q *QuoteResponseDriversItem) GetBirthdate() *time.Time {
	if q == nil {
		return nil
	}
	return q.Birthdate
}

func (q *QuoteResponseDriversItem) GetDrivingPercentage() *int {
	if q == nil {
		return nil
	}
	return q.DrivingPercentage
}

func (q *QuoteResponseDriversItem) GetExtraProperties() map[string]interface{} {
	if q == nil {
		return nil
	}
	return q.extraProperties
}

func (q *QuoteResponseDriversItem) require(field *big.Int) {
	if q.explicitFields == nil {
		q.explicitFields = big.NewInt(0)
	}
	q.explicitFields.Or(q.explicitFields, field)
}

// SetOwnerID sets the OwnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponseDriversItem) SetOwnerID(ownerID *string) {
	q.OwnerID = ownerID
	q.require(quoteResponseDriversItemFieldOwnerID)
}

// SetBirthdate sets the Birthdate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponseDriversItem) SetBirthdate(birthdate *time.Time) {
	q.Birthdate = birthdate
	q.require(quoteResponseDriversItemFieldBirthdate)
}

// SetDrivingPercentage sets the DrivingPercentage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponseDriversItem) SetDrivingPercentage(drivingPercentage *int) {
	q.DrivingPercentage = drivingPercentage
	q.require(quoteResponseDriversItemFieldDrivingPercentage)
}

func (q *QuoteResponseDriversItem) UnmarshalJSON(data []byte) error {
	type embed QuoteResponseDriversItem
	var unmarshaler = struct {
		embed
		Birthdate *internal.Date `json:"birthdate,omitempty"`
	}{
		embed: embed(*q),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*q = QuoteResponseDriversItem(unmarshaler.embed)
	q.Birthdate = unmarshaler.Birthdate.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.extraProperties = extraProperties
	q.rawJSON = json.RawMessage(data)
	return nil
}

func (q *QuoteResponseDriversItem) MarshalJSON() ([]byte, error) {
	type embed QuoteResponseDriversItem
	var marshaler = struct {
		embed
		Birthdate *internal.Date `json:"birthdate,omitempty"`
	}{
		embed:     embed(*q),
		Birthdate: internal.NewOptionalDate(q.Birthdate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (q *QuoteResponseDriversItem) String() string {
	if q == nil {
		return "<nil>"
	}
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}

var (
	quoteResponseQuotesItemFieldCompanyName = big.NewInt(1 << 0)
	quoteResponseQuotesItemFieldPrices      = big.NewInt(1 << 1)
	quoteResponseQuotesItemFieldBenefits    = big.NewInt(1 << 2)
)

type QuoteResponseQuotesItem struct {
	CompanyName *string `json:"company_name,omitempty" url:"company_name,omitempty"`
	// An array representing each price. This will have the premium and the deductible
	Prices []*QuotePrice `json:"prices,omitempty" url:"prices,omitempty"`
	// An array representing the different benefits offered by the company. Some of them are free and comes with the insurance, some are paid and optional
	Benefits []*Benefit `json:"benefits,omitempty" url:"benefits,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (q *QuoteResponseQuotesItem) GetCompanyName() *string {
	if q == nil {
		return nil
	}
	return q.CompanyName
}

func (q *QuoteResponseQuotesItem) GetPrices() []*QuotePrice {
	if q == nil {
		return nil
	}
	return q.Prices
}

func (q *QuoteResponseQuotesItem) GetBenefits() []*Benefit {
	if q == nil {
		return nil
	}
	return q.Benefits
}

func (q *QuoteResponseQuotesItem) GetExtraProperties() map[string]interface{} {
	if q == nil {
		return nil
	}
	return q.extraProperties
}

func (q *QuoteResponseQuotesItem) require(field *big.Int) {
	if q.explicitFields == nil {
		q.explicitFields = big.NewInt(0)
	}
	q.explicitFields.Or(q.explicitFields, field)
}

// SetCompanyName sets the CompanyName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponseQuotesItem) SetCompanyName(companyName *string) {
	q.CompanyName = companyName
	q.require(quoteResponseQuotesItemFieldCompanyName)
}

// SetPrices sets the Prices field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponseQuotesItem) SetPrices(prices []*QuotePrice) {
	q.Prices = prices
	q.require(quoteResponseQuotesItemFieldPrices)
}

// SetBenefits sets the Benefits field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponseQuotesItem) SetBenefits(benefits []*Benefit) {
	q.Benefits = benefits
	q.require(quoteResponseQuotesItemFieldBenefits)
}

func (q *QuoteResponseQuotesItem) UnmarshalJSON(data []byte) error {
	type unmarshaler QuoteResponseQuotesItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*q = QuoteResponseQuotesItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.extraProperties = extraProperties
	q.rawJSON = json.RawMessage(data)
	return nil
}

func (q *QuoteResponseQuotesItem) MarshalJSON() ([]byte, error) {
	type embed QuoteResponseQuotesItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (q *QuoteResponseQuotesItem) String() string {
	if q == nil {
		return "<nil>"
	}
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}

var (
	deleteQuoteRequestsIDResponseFieldMessage = big.NewInt(1 << 0)
)

type DeleteQuoteRequestsIDResponse struct {
	Message *string `json:"message,omitempty" url:"message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteQuoteRequestsIDResponse) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}

func (d *DeleteQuoteRequestsIDResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeleteQuoteRequestsIDResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteQuoteRequestsIDResponse) SetMessage(message *string) {
	d.Message = message
	d.require(deleteQuoteRequestsIDResponseFieldMessage)
}

func (d *DeleteQuoteRequestsIDResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteQuoteRequestsIDResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteQuoteRequestsIDResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteQuoteRequestsIDResponse) MarshalJSON() ([]byte, error) {
	type embed DeleteQuoteRequestsIDResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteQuoteRequestsIDResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	getQuoteRequestsResponseFieldCurrentPage  = big.NewInt(1 << 0)
	getQuoteRequestsResponseFieldData         = big.NewInt(1 << 1)
	getQuoteRequestsResponseFieldFirstPageURL = big.NewInt(1 << 2)
	getQuoteRequestsResponseFieldFrom         = big.NewInt(1 << 3)
	getQuoteRequestsResponseFieldLastPage     = big.NewInt(1 << 4)
	getQuoteRequestsResponseFieldLastPageURL  = big.NewInt(1 << 5)
	getQuoteRequestsResponseFieldLinks        = big.NewInt(1 << 6)
	getQuoteRequestsResponseFieldNextPageURL  = big.NewInt(1 << 7)
	getQuoteRequestsResponseFieldPath         = big.NewInt(1 << 8)
	getQuoteRequestsResponseFieldPerPage      = big.NewInt(1 << 9)
	getQuoteRequestsResponseFieldPrevPageURL  = big.NewInt(1 << 10)
	getQuoteRequestsResponseFieldTo           = big.NewInt(1 << 11)
	getQuoteRequestsResponseFieldTotal        = big.NewInt(1 << 12)
)

type GetQuoteRequestsResponse struct {
	CurrentPage  *int                                 `json:"current_page,omitempty" url:"current_page,omitempty"`
	Data         []*QuoteResponse                     `json:"data,omitempty" url:"data,omitempty"`
	FirstPageURL *string                              `json:"first_page_url,omitempty" url:"first_page_url,omitempty"`
	From         *int                                 `json:"from,omitempty" url:"from,omitempty"`
	LastPage     *int                                 `json:"last_page,omitempty" url:"last_page,omitempty"`
	LastPageURL  *string                              `json:"last_page_url,omitempty" url:"last_page_url,omitempty"`
	Links        []*GetQuoteRequestsResponseLinksItem `json:"links,omitempty" url:"links,omitempty"`
	NextPageURL  *string                              `json:"next_page_url,omitempty" url:"next_page_url,omitempty"`
	Path         *string                              `json:"path,omitempty" url:"path,omitempty"`
	PerPage      *int                                 `json:"per_page,omitempty" url:"per_page,omitempty"`
	PrevPageURL  *string                              `json:"prev_page_url,omitempty" url:"prev_page_url,omitempty"`
	To           *int                                 `json:"to,omitempty" url:"to,omitempty"`
	Total        *int                                 `json:"total,omitempty" url:"total,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetQuoteRequestsResponse) GetCurrentPage() *int {
	if g == nil {
		return nil
	}
	return g.CurrentPage
}

func (g *GetQuoteRequestsResponse) GetData() []*QuoteResponse {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetQuoteRequestsResponse) GetFirstPageURL() *string {
	if g == nil {
		return nil
	}
	return g.FirstPageURL
}

func (g *GetQuoteRequestsResponse) GetFrom() *int {
	if g == nil {
		return nil
	}
	return g.From
}

func (g *GetQuoteRequestsResponse) GetLastPage() *int {
	if g == nil {
		return nil
	}
	return g.LastPage
}

func (g *GetQuoteRequestsResponse) GetLastPageURL() *string {
	if g == nil {
		return nil
	}
	return g.LastPageURL
}

func (g *GetQuoteRequestsResponse) GetLinks() []*GetQuoteRequestsResponseLinksItem {
	if g == nil {
		return nil
	}
	return g.Links
}

func (g *GetQuoteRequestsResponse) GetNextPageURL() *string {
	if g == nil {
		return nil
	}
	return g.NextPageURL
}

func (g *GetQuoteRequestsResponse) GetPath() *string {
	if g == nil {
		return nil
	}
	return g.Path
}

func (g *GetQuoteRequestsResponse) GetPerPage() *int {
	if g == nil {
		return nil
	}
	return g.PerPage
}

func (g *GetQuoteRequestsResponse) GetPrevPageURL() *string {
	if g == nil {
		return nil
	}
	return g.PrevPageURL
}

func (g *GetQuoteRequestsResponse) GetTo() *int {
	if g == nil {
		return nil
	}
	return g.To
}

func (g *GetQuoteRequestsResponse) GetTotal() *int {
	if g == nil {
		return nil
	}
	return g.Total
}

func (g *GetQuoteRequestsResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetQuoteRequestsResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCurrentPage sets the CurrentPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsResponse) SetCurrentPage(currentPage *int) {
	g.CurrentPage = currentPage
	g.require(getQuoteRequestsResponseFieldCurrentPage)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsResponse) SetData(data []*QuoteResponse) {
	g.Data = data
	g.require(getQuoteRequestsResponseFieldData)
}

// SetFirstPageURL sets the FirstPageURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsResponse) SetFirstPageURL(firstPageURL *string) {
	g.FirstPageURL = firstPageURL
	g.require(getQuoteRequestsResponseFieldFirstPageURL)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsResponse) SetFrom(from *int) {
	g.From = from
	g.require(getQuoteRequestsResponseFieldFrom)
}

// SetLastPage sets the LastPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsResponse) SetLastPage(lastPage *int) {
	g.LastPage = lastPage
	g.require(getQuoteRequestsResponseFieldLastPage)
}

// SetLastPageURL sets the LastPageURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsResponse) SetLastPageURL(lastPageURL *string) {
	g.LastPageURL = lastPageURL
	g.require(getQuoteRequestsResponseFieldLastPageURL)
}

// SetLinks sets the Links field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsResponse) SetLinks(links []*GetQuoteRequestsResponseLinksItem) {
	g.Links = links
	g.require(getQuoteRequestsResponseFieldLinks)
}

// SetNextPageURL sets the NextPageURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsResponse) SetNextPageURL(nextPageURL *string) {
	g.NextPageURL = nextPageURL
	g.require(getQuoteRequestsResponseFieldNextPageURL)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsResponse) SetPath(path *string) {
	g.Path = path
	g.require(getQuoteRequestsResponseFieldPath)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsResponse) SetPerPage(perPage *int) {
	g.PerPage = perPage
	g.require(getQuoteRequestsResponseFieldPerPage)
}

// SetPrevPageURL sets the PrevPageURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsResponse) SetPrevPageURL(prevPageURL *string) {
	g.PrevPageURL = prevPageURL
	g.require(getQuoteRequestsResponseFieldPrevPageURL)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsResponse) SetTo(to *int) {
	g.To = to
	g.require(getQuoteRequestsResponseFieldTo)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsResponse) SetTotal(total *int) {
	g.Total = total
	g.require(getQuoteRequestsResponseFieldTotal)
}

func (g *GetQuoteRequestsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetQuoteRequestsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetQuoteRequestsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetQuoteRequestsResponse) MarshalJSON() ([]byte, error) {
	type embed GetQuoteRequestsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetQuoteRequestsResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getQuoteRequestsResponseLinksItemFieldURL    = big.NewInt(1 << 0)
	getQuoteRequestsResponseLinksItemFieldLabel  = big.NewInt(1 << 1)
	getQuoteRequestsResponseLinksItemFieldActive = big.NewInt(1 << 2)
)

type GetQuoteRequestsResponseLinksItem struct {
	URL    *string `json:"url,omitempty" url:"url,omitempty"`
	Label  *string `json:"label,omitempty" url:"label,omitempty"`
	Active *bool   `json:"active,omitempty" url:"active,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetQuoteRequestsResponseLinksItem) GetURL() *string {
	if g == nil {
		return nil
	}
	return g.URL
}

func (g *GetQuoteRequestsResponseLinksItem) GetLabel() *string {
	if g == nil {
		return nil
	}
	return g.Label
}

func (g *GetQuoteRequestsResponseLinksItem) GetActive() *bool {
	if g == nil {
		return nil
	}
	return g.Active
}

func (g *GetQuoteRequestsResponseLinksItem) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetQuoteRequestsResponseLinksItem) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsResponseLinksItem) SetURL(url *string) {
	g.URL = url
	g.require(getQuoteRequestsResponseLinksItemFieldURL)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsResponseLinksItem) SetLabel(label *string) {
	g.Label = label
	g.require(getQuoteRequestsResponseLinksItemFieldLabel)
}

// SetActive sets the Active field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsResponseLinksItem) SetActive(active *bool) {
	g.Active = active
	g.require(getQuoteRequestsResponseLinksItemFieldActive)
}

func (g *GetQuoteRequestsResponseLinksItem) UnmarshalJSON(data []byte) error {
	type unmarshaler GetQuoteRequestsResponseLinksItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetQuoteRequestsResponseLinksItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetQuoteRequestsResponseLinksItem) MarshalJSON() ([]byte, error) {
	type embed GetQuoteRequestsResponseLinksItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetQuoteRequestsResponseLinksItem) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	postQuoteRequestsRequestDriversItemFieldOwnerID           = big.NewInt(1 << 0)
	postQuoteRequestsRequestDriversItemFieldBirthdate         = big.NewInt(1 << 1)
	postQuoteRequestsRequestDriversItemFieldDrivingPercentage = big.NewInt(1 << 2)
)

type PostQuoteRequestsRequestDriversItem struct {
	// Driver's national ID. Must be 10 digits starting with 1, 2, or 7.
	OwnerID string `json:"owner_id" url:"owner_id"`
	// Driver's birthdate in YYYY-MM-DD format.
	Birthdate time.Time `json:"birthdate" url:"birthdate" format:"date"`
	// Percentage of driving for this driver. Valid values are 25, 50, 75, or 100. The sum of all drivers' percentages must equal 100.
	DrivingPercentage int `json:"driving_percentage" url:"driving_percentage"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PostQuoteRequestsRequestDriversItem) GetOwnerID() string {
	if p == nil {
		return ""
	}
	return p.OwnerID
}

func (p *PostQuoteRequestsRequestDriversItem) GetBirthdate() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.Birthdate
}

func (p *PostQuoteRequestsRequestDriversItem) GetDrivingPercentage() int {
	if p == nil {
		return 0
	}
	return p.DrivingPercentage
}

func (p *PostQuoteRequestsRequestDriversItem) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PostQuoteRequestsRequestDriversItem) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetOwnerID sets the OwnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequestDriversItem) SetOwnerID(ownerID string) {
	p.OwnerID = ownerID
	p.require(postQuoteRequestsRequestDriversItemFieldOwnerID)
}

// SetBirthdate sets the Birthdate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequestDriversItem) SetBirthdate(birthdate time.Time) {
	p.Birthdate = birthdate
	p.require(postQuoteRequestsRequestDriversItemFieldBirthdate)
}

// SetDrivingPercentage sets the DrivingPercentage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequestDriversItem) SetDrivingPercentage(drivingPercentage int) {
	p.DrivingPercentage = drivingPercentage
	p.require(postQuoteRequestsRequestDriversItemFieldDrivingPercentage)
}

func (p *PostQuoteRequestsRequestDriversItem) UnmarshalJSON(data []byte) error {
	type embed PostQuoteRequestsRequestDriversItem
	var unmarshaler = struct {
		embed
		Birthdate *internal.Date `json:"birthdate"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = PostQuoteRequestsRequestDriversItem(unmarshaler.embed)
	p.Birthdate = unmarshaler.Birthdate.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PostQuoteRequestsRequestDriversItem) MarshalJSON() ([]byte, error) {
	type embed PostQuoteRequestsRequestDriversItem
	var marshaler = struct {
		embed
		Birthdate *internal.Date `json:"birthdate"`
	}{
		embed:     embed(*p),
		Birthdate: internal.NewDate(p.Birthdate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PostQuoteRequestsRequestDriversItem) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
