// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/yasminaai/motor-go-sdk/internal"
	big "math/big"
	time "time"
)

var (
	deleteQuoteRequestsIDRequestFieldID = big.NewInt(1 << 0)
)

type DeleteQuoteRequestsIDRequest struct {
	ID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteQuoteRequestsIDRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteQuoteRequestsIDRequest) SetID(id int) {
	d.ID = id
	d.require(deleteQuoteRequestsIDRequestFieldID)
}

var (
	getQuoteRequestsRequestFieldDateFrom          = big.NewInt(1 << 0)
	getQuoteRequestsRequestFieldDateTo            = big.NewInt(1 << 1)
	getQuoteRequestsRequestFieldPerPage           = big.NewInt(1 << 2)
	getQuoteRequestsRequestFieldIncludeAggregates = big.NewInt(1 << 3)
)

type GetQuoteRequestsRequest struct {
	// Inclusive lower bound for quote request creation date.
	DateFrom *time.Time `json:"-" url:"date_from,omitempty" format:"date"`
	// Inclusive upper bound for quote request creation date.
	DateTo *time.Time `json:"-" url:"date_to,omitempty" format:"date"`
	// Number of quote requests to return per page.
	PerPage *int `json:"-" url:"per_page,omitempty"`
	// When true, includes quote request totals and monthly buckets for the filtered result set.
	IncludeAggregates *bool `json:"-" url:"include_aggregates,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetQuoteRequestsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetDateFrom sets the DateFrom field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsRequest) SetDateFrom(dateFrom *time.Time) {
	g.DateFrom = dateFrom
	g.require(getQuoteRequestsRequestFieldDateFrom)
}

// SetDateTo sets the DateTo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsRequest) SetDateTo(dateTo *time.Time) {
	g.DateTo = dateTo
	g.require(getQuoteRequestsRequestFieldDateTo)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsRequest) SetPerPage(perPage *int) {
	g.PerPage = perPage
	g.require(getQuoteRequestsRequestFieldPerPage)
}

// SetIncludeAggregates sets the IncludeAggregates field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsRequest) SetIncludeAggregates(includeAggregates *bool) {
	g.IncludeAggregates = includeAggregates
	g.require(getQuoteRequestsRequestFieldIncludeAggregates)
}

var (
	postQuoteRequestsRequestFieldAcceptLanguage      = big.NewInt(1 << 0)
	postQuoteRequestsRequestFieldOtp                 = big.NewInt(1 << 1)
	postQuoteRequestsRequestFieldOwnerID             = big.NewInt(1 << 2)
	postQuoteRequestsRequestFieldEmail               = big.NewInt(1 << 3)
	postQuoteRequestsRequestFieldPhone               = big.NewInt(1 << 4)
	postQuoteRequestsRequestFieldBirthdate           = big.NewInt(1 << 5)
	postQuoteRequestsRequestFieldCarSequenceNumber   = big.NewInt(1 << 6)
	postQuoteRequestsRequestFieldCustomNumber        = big.NewInt(1 << 7)
	postQuoteRequestsRequestFieldIsOwnershipTransfer = big.NewInt(1 << 8)
	postQuoteRequestsRequestFieldCurrentCarOwnerID   = big.NewInt(1 << 9)
	postQuoteRequestsRequestFieldCarEstimatedCost    = big.NewInt(1 << 10)
	postQuoteRequestsRequestFieldCarModelYear        = big.NewInt(1 << 11)
	postQuoteRequestsRequestFieldStartDate           = big.NewInt(1 << 12)
	postQuoteRequestsRequestFieldDrivers             = big.NewInt(1 << 13)
)

type PostQuoteRequestsRequest struct {
	// Set to ar to receive Arabic-localized quote content.
	AcceptLanguage *PostQuoteRequestsRequestAcceptLanguage `json:"-" url:"-"`
	// The OTP received by the customer from the Request OTP API
	Otp string `json:"otp" url:"-"`
	// Owner ID must be 10 digits starting with 1, 2, or 7
	OwnerID string `json:"owner_id" url:"-"`
	// Email address must be valid and belongs to the customer
	Email *string `json:"email,omitempty" url:"-"`
	// Phone number must start with 05 and be 10 digits
	Phone string `json:"phone" url:"-"`
	// Birthdate in YYYY-MM-DD format
	Birthdate time.Time `json:"birthdate" url:"-" format:"date"`
	// Car sequence number must be 8 or 9 digits
	CarSequenceNumber *string `json:"car_sequence_number,omitempty" url:"-"`
	// Custom car number between 1000000 and 9999999999 (for newly imported cars)
	CustomNumber *string `json:"custom_number,omitempty" url:"-"`
	// Indicates if the ownership is being transferred
	IsOwnershipTransfer *bool `json:"is_ownership_transfer,omitempty" url:"-"`
	// Required if is_ownership_transfer is true; 10 digits starting with 1,2,7
	CurrentCarOwnerID *string `json:"current_car_owner_id,omitempty" url:"-"`
	// Estimated cost of the car
	CarEstimatedCost float64 `json:"car_estimated_cost" url:"-"`
	// Car model year between 1950 and next year
	CarModelYear *int `json:"car_model_year,omitempty" url:"-"`
	// Desired policy start date in YYYY-MM-DD. Must be between tomorrow and 28 days from today (inclusive). The platform validates this range server-side.
	StartDate *time.Time `json:"start_date,omitempty" url:"-" format:"date"`
	// List of drivers for the vehicle. When provided, the sum of all driving_percentage values must equal 100, and the owner must be included among the drivers.
	Drivers []*PostQuoteRequestsRequestDriversItem `json:"drivers,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostQuoteRequestsRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetAcceptLanguage sets the AcceptLanguage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetAcceptLanguage(acceptLanguage *PostQuoteRequestsRequestAcceptLanguage) {
	p.AcceptLanguage = acceptLanguage
	p.require(postQuoteRequestsRequestFieldAcceptLanguage)
}

// SetOtp sets the Otp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetOtp(otp string) {
	p.Otp = otp
	p.require(postQuoteRequestsRequestFieldOtp)
}

// SetOwnerID sets the OwnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetOwnerID(ownerID string) {
	p.OwnerID = ownerID
	p.require(postQuoteRequestsRequestFieldOwnerID)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetEmail(email *string) {
	p.Email = email
	p.require(postQuoteRequestsRequestFieldEmail)
}

// SetPhone sets the Phone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetPhone(phone string) {
	p.Phone = phone
	p.require(postQuoteRequestsRequestFieldPhone)
}

// SetBirthdate sets the Birthdate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetBirthdate(birthdate time.Time) {
	p.Birthdate = birthdate
	p.require(postQuoteRequestsRequestFieldBirthdate)
}

// SetCarSequenceNumber sets the CarSequenceNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetCarSequenceNumber(carSequenceNumber *string) {
	p.CarSequenceNumber = carSequenceNumber
	p.require(postQuoteRequestsRequestFieldCarSequenceNumber)
}

// SetCustomNumber sets the CustomNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetCustomNumber(customNumber *string) {
	p.CustomNumber = customNumber
	p.require(postQuoteRequestsRequestFieldCustomNumber)
}

// SetIsOwnershipTransfer sets the IsOwnershipTransfer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetIsOwnershipTransfer(isOwnershipTransfer *bool) {
	p.IsOwnershipTransfer = isOwnershipTransfer
	p.require(postQuoteRequestsRequestFieldIsOwnershipTransfer)
}

// SetCurrentCarOwnerID sets the CurrentCarOwnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetCurrentCarOwnerID(currentCarOwnerID *string) {
	p.CurrentCarOwnerID = currentCarOwnerID
	p.require(postQuoteRequestsRequestFieldCurrentCarOwnerID)
}

// SetCarEstimatedCost sets the CarEstimatedCost field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetCarEstimatedCost(carEstimatedCost float64) {
	p.CarEstimatedCost = carEstimatedCost
	p.require(postQuoteRequestsRequestFieldCarEstimatedCost)
}

// SetCarModelYear sets the CarModelYear field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetCarModelYear(carModelYear *int) {
	p.CarModelYear = carModelYear
	p.require(postQuoteRequestsRequestFieldCarModelYear)
}

// SetStartDate sets the StartDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetStartDate(startDate *time.Time) {
	p.StartDate = startDate
	p.require(postQuoteRequestsRequestFieldStartDate)
}

// SetDrivers sets the Drivers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequest) SetDrivers(drivers []*PostQuoteRequestsRequestDriversItem) {
	p.Drivers = drivers
	p.require(postQuoteRequestsRequestFieldDrivers)
}

func (p *PostQuoteRequestsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler PostQuoteRequestsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = PostQuoteRequestsRequest(body)
	return nil
}

func (p *PostQuoteRequestsRequest) MarshalJSON() ([]byte, error) {
	type embed PostQuoteRequestsRequest
	var marshaler = struct {
		embed
		Birthdate *internal.Date `json:"birthdate"`
		StartDate *internal.Date `json:"start_date,omitempty"`
	}{
		embed:     embed(*p),
		Birthdate: internal.NewDate(p.Birthdate),
		StartDate: internal.NewOptionalDate(p.StartDate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getQuoteRequestsIDRequestFieldID = big.NewInt(1 << 0)
)

type GetQuoteRequestsIDRequest struct {
	ID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetQuoteRequestsIDRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQuoteRequestsIDRequest) SetID(id int) {
	g.ID = id
	g.require(getQuoteRequestsIDRequestFieldID)
}

var (
	benefitFieldQuoteBenefitID = big.NewInt(1 << 0)
	benefitFieldID             = big.NewInt(1 << 1)
	benefitFieldName           = big.NewInt(1 << 2)
	benefitFieldNameAr         = big.NewInt(1 << 3)
	benefitFieldAmount         = big.NewInt(1 << 4)
	benefitFieldVat            = big.NewInt(1 << 5)
	benefitFieldURL            = big.NewInt(1 << 6)
)

type Benefit struct {
	QuoteBenefitID *string `json:"quote_benefit_id,omitempty" url:"quote_benefit_id,omitempty"`
	ID             *string `json:"id,omitempty" url:"id,omitempty"`
	Name           *string `json:"name,omitempty" url:"name,omitempty"`
	// Arabic name of the benefit. Use this field instead of `name` when rendering Arabic UIs.
	NameAr *string  `json:"name_ar,omitempty" url:"name_ar,omitempty"`
	Amount *float64 `json:"amount,omitempty" url:"amount,omitempty"`
	Vat    *float64 `json:"vat,omitempty" url:"vat,omitempty"`
	URL    *string  `json:"url,omitempty" url:"url,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *Benefit) GetQuoteBenefitID() *string {
	if b == nil {
		return nil
	}
	return b.QuoteBenefitID
}

func (b *Benefit) GetID() *string {
	if b == nil {
		return nil
	}
	return b.ID
}

func (b *Benefit) GetName() *string {
	if b == nil {
		return nil
	}
	return b.Name
}

func (b *Benefit) GetNameAr() *string {
	if b == nil {
		return nil
	}
	return b.NameAr
}

func (b *Benefit) GetAmount() *float64 {
	if b == nil {
		return nil
	}
	return b.Amount
}

func (b *Benefit) GetVat() *float64 {
	if b == nil {
		return nil
	}
	return b.Vat
}

func (b *Benefit) GetURL() *string {
	if b == nil {
		return nil
	}
	return b.URL
}

func (b *Benefit) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *Benefit) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetQuoteBenefitID sets the QuoteBenefitID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Benefit) SetQuoteBenefitID(quoteBenefitID *string) {
	b.QuoteBenefitID = quoteBenefitID
	b.require(benefitFieldQuoteBenefitID)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Benefit) SetID(id *string) {
	b.ID = id
	b.require(benefitFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Benefit) SetName(name *string) {
	b.Name = name
	b.require(benefitFieldName)
}

// SetNameAr sets the NameAr field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Benefit) SetNameAr(nameAr *string) {
	b.NameAr = nameAr
	b.require(benefitFieldNameAr)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Benefit) SetAmount(amount *float64) {
	b.Amount = amount
	b.require(benefitFieldAmount)
}

// SetVat sets the Vat field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Benefit) SetVat(vat *float64) {
	b.Vat = vat
	b.require(benefitFieldVat)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Benefit) SetURL(url *string) {
	b.URL = url
	b.require(benefitFieldURL)
}

func (b *Benefit) UnmarshalJSON(data []byte) error {
	type unmarshaler Benefit
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = Benefit(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *Benefit) MarshalJSON() ([]byte, error) {
	type embed Benefit
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *Benefit) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	paginatedQuoteResponseFieldCurrentPage  = big.NewInt(1 << 0)
	paginatedQuoteResponseFieldData         = big.NewInt(1 << 1)
	paginatedQuoteResponseFieldFirstPageURL = big.NewInt(1 << 2)
	paginatedQuoteResponseFieldFrom         = big.NewInt(1 << 3)
	paginatedQuoteResponseFieldLastPage     = big.NewInt(1 << 4)
	paginatedQuoteResponseFieldLastPageURL  = big.NewInt(1 << 5)
	paginatedQuoteResponseFieldLinks        = big.NewInt(1 << 6)
	paginatedQuoteResponseFieldNextPageURL  = big.NewInt(1 << 7)
	paginatedQuoteResponseFieldPath         = big.NewInt(1 << 8)
	paginatedQuoteResponseFieldPerPage      = big.NewInt(1 << 9)
	paginatedQuoteResponseFieldPrevPageURL  = big.NewInt(1 << 10)
	paginatedQuoteResponseFieldTo           = big.NewInt(1 << 11)
	paginatedQuoteResponseFieldTotal        = big.NewInt(1 << 12)
	paginatedQuoteResponseFieldAggregates   = big.NewInt(1 << 13)
)

type PaginatedQuoteResponse struct {
	CurrentPage  *int                    `json:"current_page,omitempty" url:"current_page,omitempty"`
	Data         []*QuoteResponse        `json:"data,omitempty" url:"data,omitempty"`
	FirstPageURL *string                 `json:"first_page_url,omitempty" url:"first_page_url,omitempty"`
	From         *int                    `json:"from,omitempty" url:"from,omitempty"`
	LastPage     *int                    `json:"last_page,omitempty" url:"last_page,omitempty"`
	LastPageURL  *string                 `json:"last_page_url,omitempty" url:"last_page_url,omitempty"`
	Links        []*PaginationLink       `json:"links,omitempty" url:"links,omitempty"`
	NextPageURL  *string                 `json:"next_page_url,omitempty" url:"next_page_url,omitempty"`
	Path         *string                 `json:"path,omitempty" url:"path,omitempty"`
	PerPage      *int                    `json:"per_page,omitempty" url:"per_page,omitempty"`
	PrevPageURL  *string                 `json:"prev_page_url,omitempty" url:"prev_page_url,omitempty"`
	To           *int                    `json:"to,omitempty" url:"to,omitempty"`
	Total        *int                    `json:"total,omitempty" url:"total,omitempty"`
	Aggregates   *QuoteRequestAggregates `json:"aggregates,omitempty" url:"aggregates,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaginatedQuoteResponse) GetCurrentPage() *int {
	if p == nil {
		return nil
	}
	return p.CurrentPage
}

func (p *PaginatedQuoteResponse) GetData() []*QuoteResponse {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PaginatedQuoteResponse) GetFirstPageURL() *string {
	if p == nil {
		return nil
	}
	return p.FirstPageURL
}

func (p *PaginatedQuoteResponse) GetFrom() *int {
	if p == nil {
		return nil
	}
	return p.From
}

func (p *PaginatedQuoteResponse) GetLastPage() *int {
	if p == nil {
		return nil
	}
	return p.LastPage
}

func (p *PaginatedQuoteResponse) GetLastPageURL() *string {
	if p == nil {
		return nil
	}
	return p.LastPageURL
}

func (p *PaginatedQuoteResponse) GetLinks() []*PaginationLink {
	if p == nil {
		return nil
	}
	return p.Links
}

func (p *PaginatedQuoteResponse) GetNextPageURL() *string {
	if p == nil {
		return nil
	}
	return p.NextPageURL
}

func (p *PaginatedQuoteResponse) GetPath() *string {
	if p == nil {
		return nil
	}
	return p.Path
}

func (p *PaginatedQuoteResponse) GetPerPage() *int {
	if p == nil {
		return nil
	}
	return p.PerPage
}

func (p *PaginatedQuoteResponse) GetPrevPageURL() *string {
	if p == nil {
		return nil
	}
	return p.PrevPageURL
}

func (p *PaginatedQuoteResponse) GetTo() *int {
	if p == nil {
		return nil
	}
	return p.To
}

func (p *PaginatedQuoteResponse) GetTotal() *int {
	if p == nil {
		return nil
	}
	return p.Total
}

func (p *PaginatedQuoteResponse) GetAggregates() *QuoteRequestAggregates {
	if p == nil {
		return nil
	}
	return p.Aggregates
}

func (p *PaginatedQuoteResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PaginatedQuoteResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetCurrentPage sets the CurrentPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedQuoteResponse) SetCurrentPage(currentPage *int) {
	p.CurrentPage = currentPage
	p.require(paginatedQuoteResponseFieldCurrentPage)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedQuoteResponse) SetData(data []*QuoteResponse) {
	p.Data = data
	p.require(paginatedQuoteResponseFieldData)
}

// SetFirstPageURL sets the FirstPageURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedQuoteResponse) SetFirstPageURL(firstPageURL *string) {
	p.FirstPageURL = firstPageURL
	p.require(paginatedQuoteResponseFieldFirstPageURL)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedQuoteResponse) SetFrom(from *int) {
	p.From = from
	p.require(paginatedQuoteResponseFieldFrom)
}

// SetLastPage sets the LastPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedQuoteResponse) SetLastPage(lastPage *int) {
	p.LastPage = lastPage
	p.require(paginatedQuoteResponseFieldLastPage)
}

// SetLastPageURL sets the LastPageURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedQuoteResponse) SetLastPageURL(lastPageURL *string) {
	p.LastPageURL = lastPageURL
	p.require(paginatedQuoteResponseFieldLastPageURL)
}

// SetLinks sets the Links field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedQuoteResponse) SetLinks(links []*PaginationLink) {
	p.Links = links
	p.require(paginatedQuoteResponseFieldLinks)
}

// SetNextPageURL sets the NextPageURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedQuoteResponse) SetNextPageURL(nextPageURL *string) {
	p.NextPageURL = nextPageURL
	p.require(paginatedQuoteResponseFieldNextPageURL)
}

// SetPath sets the Path field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedQuoteResponse) SetPath(path *string) {
	p.Path = path
	p.require(paginatedQuoteResponseFieldPath)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedQuoteResponse) SetPerPage(perPage *int) {
	p.PerPage = perPage
	p.require(paginatedQuoteResponseFieldPerPage)
}

// SetPrevPageURL sets the PrevPageURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedQuoteResponse) SetPrevPageURL(prevPageURL *string) {
	p.PrevPageURL = prevPageURL
	p.require(paginatedQuoteResponseFieldPrevPageURL)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedQuoteResponse) SetTo(to *int) {
	p.To = to
	p.require(paginatedQuoteResponseFieldTo)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedQuoteResponse) SetTotal(total *int) {
	p.Total = total
	p.require(paginatedQuoteResponseFieldTotal)
}

// SetAggregates sets the Aggregates field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedQuoteResponse) SetAggregates(aggregates *QuoteRequestAggregates) {
	p.Aggregates = aggregates
	p.require(paginatedQuoteResponseFieldAggregates)
}

func (p *PaginatedQuoteResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PaginatedQuoteResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaginatedQuoteResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaginatedQuoteResponse) MarshalJSON() ([]byte, error) {
	type embed PaginatedQuoteResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PaginatedQuoteResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	quotePriceFieldQuotePriceID  = big.NewInt(1 << 0)
	quotePriceFieldDeductible    = big.NewInt(1 << 1)
	quotePriceFieldSubtotal      = big.NewInt(1 << 2)
	quotePriceFieldVatPercentage = big.NewInt(1 << 3)
	quotePriceFieldVat           = big.NewInt(1 << 4)
	quotePriceFieldTotal         = big.NewInt(1 << 5)
)

type QuotePrice struct {
	QuotePriceID  *string  `json:"quote_price_id,omitempty" url:"quote_price_id,omitempty"`
	Deductible    *float64 `json:"deductible,omitempty" url:"deductible,omitempty"`
	Subtotal      *float64 `json:"subtotal,omitempty" url:"subtotal,omitempty"`
	VatPercentage *float64 `json:"vat_percentage,omitempty" url:"vat_percentage,omitempty"`
	Vat           *float64 `json:"vat,omitempty" url:"vat,omitempty"`
	Total         *float64 `json:"total,omitempty" url:"total,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (q *QuotePrice) GetQuotePriceID() *string {
	if q == nil {
		return nil
	}
	return q.QuotePriceID
}

func (q *QuotePrice) GetDeductible() *float64 {
	if q == nil {
		return nil
	}
	return q.Deductible
}

func (q *QuotePrice) GetSubtotal() *float64 {
	if q == nil {
		return nil
	}
	return q.Subtotal
}

func (q *QuotePrice) GetVatPercentage() *float64 {
	if q == nil {
		return nil
	}
	return q.VatPercentage
}

func (q *QuotePrice) GetVat() *float64 {
	if q == nil {
		return nil
	}
	return q.Vat
}

func (q *QuotePrice) GetTotal() *float64 {
	if q == nil {
		return nil
	}
	return q.Total
}

func (q *QuotePrice) GetExtraProperties() map[string]interface{} {
	if q == nil {
		return nil
	}
	return q.extraProperties
}

func (q *QuotePrice) require(field *big.Int) {
	if q.explicitFields == nil {
		q.explicitFields = big.NewInt(0)
	}
	q.explicitFields.Or(q.explicitFields, field)
}

// SetQuotePriceID sets the QuotePriceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuotePrice) SetQuotePriceID(quotePriceID *string) {
	q.QuotePriceID = quotePriceID
	q.require(quotePriceFieldQuotePriceID)
}

// SetDeductible sets the Deductible field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuotePrice) SetDeductible(deductible *float64) {
	q.Deductible = deductible
	q.require(quotePriceFieldDeductible)
}

// SetSubtotal sets the Subtotal field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuotePrice) SetSubtotal(subtotal *float64) {
	q.Subtotal = subtotal
	q.require(quotePriceFieldSubtotal)
}

// SetVatPercentage sets the VatPercentage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuotePrice) SetVatPercentage(vatPercentage *float64) {
	q.VatPercentage = vatPercentage
	q.require(quotePriceFieldVatPercentage)
}

// SetVat sets the Vat field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuotePrice) SetVat(vat *float64) {
	q.Vat = vat
	q.require(quotePriceFieldVat)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuotePrice) SetTotal(total *float64) {
	q.Total = total
	q.require(quotePriceFieldTotal)
}

func (q *QuotePrice) UnmarshalJSON(data []byte) error {
	type unmarshaler QuotePrice
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*q = QuotePrice(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.extraProperties = extraProperties
	q.rawJSON = json.RawMessage(data)
	return nil
}

func (q *QuotePrice) MarshalJSON() ([]byte, error) {
	type embed QuotePrice
	var marshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (q *QuotePrice) String() string {
	if q == nil {
		return "<nil>"
	}
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}

// Returned only when include_aggregates is true.
var (
	quoteRequestAggregatesFieldTotalCount = big.NewInt(1 << 0)
	quoteRequestAggregatesFieldByMonth    = big.NewInt(1 << 1)
)

type QuoteRequestAggregates struct {
	TotalCount *int `json:"total_count,omitempty" url:"total_count,omitempty"`
	// Monthly quote request counts keyed by YYYY-MM.
	ByMonth map[string]int `json:"by_month,omitempty" url:"by_month,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (q *QuoteRequestAggregates) GetTotalCount() *int {
	if q == nil {
		return nil
	}
	return q.TotalCount
}

func (q *QuoteRequestAggregates) GetByMonth() map[string]int {
	if q == nil {
		return nil
	}
	return q.ByMonth
}

func (q *QuoteRequestAggregates) GetExtraProperties() map[string]interface{} {
	if q == nil {
		return nil
	}
	return q.extraProperties
}

func (q *QuoteRequestAggregates) require(field *big.Int) {
	if q.explicitFields == nil {
		q.explicitFields = big.NewInt(0)
	}
	q.explicitFields.Or(q.explicitFields, field)
}

// SetTotalCount sets the TotalCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteRequestAggregates) SetTotalCount(totalCount *int) {
	q.TotalCount = totalCount
	q.require(quoteRequestAggregatesFieldTotalCount)
}

// SetByMonth sets the ByMonth field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteRequestAggregates) SetByMonth(byMonth map[string]int) {
	q.ByMonth = byMonth
	q.require(quoteRequestAggregatesFieldByMonth)
}

func (q *QuoteRequestAggregates) UnmarshalJSON(data []byte) error {
	type unmarshaler QuoteRequestAggregates
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*q = QuoteRequestAggregates(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.extraProperties = extraProperties
	q.rawJSON = json.RawMessage(data)
	return nil
}

func (q *QuoteRequestAggregates) MarshalJSON() ([]byte, error) {
	type embed QuoteRequestAggregates
	var marshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (q *QuoteRequestAggregates) String() string {
	if q == nil {
		return "<nil>"
	}
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}

var (
	quoteResponseFieldOwnerID             = big.NewInt(1 << 0)
	quoteResponseFieldPhone               = big.NewInt(1 << 1)
	quoteResponseFieldBirthdate           = big.NewInt(1 << 2)
	quoteResponseFieldCarSequenceNumber   = big.NewInt(1 << 3)
	quoteResponseFieldCustomNumber        = big.NewInt(1 << 4)
	quoteResponseFieldIsOwnershipTransfer = big.NewInt(1 << 5)
	quoteResponseFieldCarEstimatedCost    = big.NewInt(1 << 6)
	quoteResponseFieldCarModelYear        = big.NewInt(1 << 7)
	quoteResponseFieldStartDate           = big.NewInt(1 << 8)
	quoteResponseFieldDrivers             = big.NewInt(1 << 9)
	quoteResponseFieldQuotes              = big.NewInt(1 << 10)
	quoteResponseFieldClientID            = big.NewInt(1 << 11)
	quoteResponseFieldUpdatedAt           = big.NewInt(1 << 12)
	quoteResponseFieldCreatedAt           = big.NewInt(1 << 13)
	quoteResponseFieldID                  = big.NewInt(1 << 14)
)

type QuoteResponse struct {
	// The owner’s national ID or Iqama ID
	OwnerID *int `json:"owner_id,omitempty" url:"owner_id,omitempty"`
	// The owner's phone number
	Phone *string `json:"phone,omitempty" url:"phone,omitempty"`
	// The owner's birthdate. Hijri for Saudi nationals, Gregorian for others
	Birthdate *time.Time `json:"birthdate,omitempty" url:"birthdate,omitempty" format:"date"`
	// The car sequence number from 9 digits
	CarSequenceNumber *int `json:"car_sequence_number,omitempty" url:"car_sequence_number,omitempty"`
	// Custom car number for newly imported cars (present when `custom_number` was used in the request)
	CustomNumber *string `json:"custom_number,omitempty" url:"custom_number,omitempty"`
	// Whether it was a car transfer or not
	IsOwnershipTransfer *bool `json:"is_ownership_transfer,omitempty" url:"is_ownership_transfer,omitempty"`
	// The estimated cost of the car
	CarEstimatedCost *float64 `json:"car_estimated_cost,omitempty" url:"car_estimated_cost,omitempty"`
	// The car model year
	CarModelYear *int `json:"car_model_year,omitempty" url:"car_model_year,omitempty"`
	// Requested policy start date in YYYY-MM-DD. Returned if provided in the quote request.
	StartDate *time.Time `json:"start_date,omitempty" url:"start_date,omitempty" format:"date"`
	// List of drivers associated with this quote request. Returned if drivers were provided in the request.
	Drivers []*QuoteResponseDriversItem `json:"drivers,omitempty" url:"drivers,omitempty"`
	// An array representing each insurance company quote. Each item has the company name, the prices, and the benefits.
	Quotes []*QuoteResponseQuotesItem `json:"quotes,omitempty" url:"quotes,omitempty"`
	// Your own client ID
	ClientID *string `json:"client_id,omitempty" url:"client_id,omitempty"`
	// In case of an update on this quote, this date will change
	UpdatedAt *time.Time `json:"updated_at,omitempty" url:"updated_at,omitempty"`
	// When was the quote requested
	CreatedAt *time.Time `json:"created_at,omitempty" url:"created_at,omitempty"`
	// Yasmina ID for the quote. You can use it to delete items or showing it again to the customer
	ID *int `json:"id,omitempty" url:"id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (q *QuoteResponse) GetOwnerID() *int {
	if q == nil {
		return nil
	}
	return q.OwnerID
}

func (q *QuoteResponse) GetPhone() *string {
	if q == nil {
		return nil
	}
	return q.Phone
}

func (q *QuoteResponse) GetBirthdate() *time.Time {
	if q == nil {
		return nil
	}
	return q.Birthdate
}

func (q *QuoteResponse) GetCarSequenceNumber() *int {
	if q == nil {
		return nil
	}
	return q.CarSequenceNumber
}

func (q *QuoteResponse) GetCustomNumber() *string {
	if q == nil {
		return nil
	}
	return q.CustomNumber
}

func (q *QuoteResponse) GetIsOwnershipTransfer() *bool {
	if q == nil {
		return nil
	}
	return q.IsOwnershipTransfer
}

func (q *QuoteResponse) GetCarEstimatedCost() *float64 {
	if q == nil {
		return nil
	}
	return q.CarEstimatedCost
}

func (q *QuoteResponse) GetCarModelYear() *int {
	if q == nil {
		return nil
	}
	return q.CarModelYear
}

func (q *QuoteResponse) GetStartDate() *time.Time {
	if q == nil {
		return nil
	}
	return q.StartDate
}

func (q *QuoteResponse) GetDrivers() []*QuoteResponseDriversItem {
	if q == nil {
		return nil
	}
	return q.Drivers
}

func (q *QuoteResponse) GetQuotes() []*QuoteResponseQuotesItem {
	if q == nil {
		return nil
	}
	return q.Quotes
}

func (q *QuoteResponse) GetClientID() *string {
	if q == nil {
		return nil
	}
	return q.ClientID
}

func (q *QuoteResponse) GetUpdatedAt() *time.Time {
	if q == nil {
		return nil
	}
	return q.UpdatedAt
}

func (q *QuoteResponse) GetCreatedAt() *time.Time {
	if q == nil {
		return nil
	}
	return q.CreatedAt
}

func (q *QuoteResponse) GetID() *int {
	if q == nil {
		return nil
	}
	return q.ID
}

func (q *QuoteResponse) GetExtraProperties() map[string]interface{} {
	if q == nil {
		return nil
	}
	return q.extraProperties
}

func (q *QuoteResponse) require(field *big.Int) {
	if q.explicitFields == nil {
		q.explicitFields = big.NewInt(0)
	}
	q.explicitFields.Or(q.explicitFields, field)
}

// SetOwnerID sets the OwnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetOwnerID(ownerID *int) {
	q.OwnerID = ownerID
	q.require(quoteResponseFieldOwnerID)
}

// SetPhone sets the Phone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetPhone(phone *string) {
	q.Phone = phone
	q.require(quoteResponseFieldPhone)
}

// SetBirthdate sets the Birthdate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetBirthdate(birthdate *time.Time) {
	q.Birthdate = birthdate
	q.require(quoteResponseFieldBirthdate)
}

// SetCarSequenceNumber sets the CarSequenceNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetCarSequenceNumber(carSequenceNumber *int) {
	q.CarSequenceNumber = carSequenceNumber
	q.require(quoteResponseFieldCarSequenceNumber)
}

// SetCustomNumber sets the CustomNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetCustomNumber(customNumber *string) {
	q.CustomNumber = customNumber
	q.require(quoteResponseFieldCustomNumber)
}

// SetIsOwnershipTransfer sets the IsOwnershipTransfer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetIsOwnershipTransfer(isOwnershipTransfer *bool) {
	q.IsOwnershipTransfer = isOwnershipTransfer
	q.require(quoteResponseFieldIsOwnershipTransfer)
}

// SetCarEstimatedCost sets the CarEstimatedCost field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetCarEstimatedCost(carEstimatedCost *float64) {
	q.CarEstimatedCost = carEstimatedCost
	q.require(quoteResponseFieldCarEstimatedCost)
}

// SetCarModelYear sets the CarModelYear field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetCarModelYear(carModelYear *int) {
	q.CarModelYear = carModelYear
	q.require(quoteResponseFieldCarModelYear)
}

// SetStartDate sets the StartDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetStartDate(startDate *time.Time) {
	q.StartDate = startDate
	q.require(quoteResponseFieldStartDate)
}

// SetDrivers sets the Drivers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetDrivers(drivers []*QuoteResponseDriversItem) {
	q.Drivers = drivers
	q.require(quoteResponseFieldDrivers)
}

// SetQuotes sets the Quotes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetQuotes(quotes []*QuoteResponseQuotesItem) {
	q.Quotes = quotes
	q.require(quoteResponseFieldQuotes)
}

// SetClientID sets the ClientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetClientID(clientID *string) {
	q.ClientID = clientID
	q.require(quoteResponseFieldClientID)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetUpdatedAt(updatedAt *time.Time) {
	q.UpdatedAt = updatedAt
	q.require(quoteResponseFieldUpdatedAt)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetCreatedAt(createdAt *time.Time) {
	q.CreatedAt = createdAt
	q.require(quoteResponseFieldCreatedAt)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponse) SetID(id *int) {
	q.ID = id
	q.require(quoteResponseFieldID)
}

func (q *QuoteResponse) UnmarshalJSON(data []byte) error {
	type embed QuoteResponse
	var unmarshaler = struct {
		embed
		Birthdate *internal.Date     `json:"birthdate,omitempty"`
		StartDate *internal.Date     `json:"start_date,omitempty"`
		UpdatedAt *internal.DateTime `json:"updated_at,omitempty"`
		CreatedAt *internal.DateTime `json:"created_at,omitempty"`
	}{
		embed: embed(*q),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*q = QuoteResponse(unmarshaler.embed)
	q.Birthdate = unmarshaler.Birthdate.TimePtr()
	q.StartDate = unmarshaler.StartDate.TimePtr()
	q.UpdatedAt = unmarshaler.UpdatedAt.TimePtr()
	q.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.extraProperties = extraProperties
	q.rawJSON = json.RawMessage(data)
	return nil
}

func (q *QuoteResponse) MarshalJSON() ([]byte, error) {
	type embed QuoteResponse
	var marshaler = struct {
		embed
		Birthdate *internal.Date     `json:"birthdate,omitempty"`
		StartDate *internal.Date     `json:"start_date,omitempty"`
		UpdatedAt *internal.DateTime `json:"updated_at,omitempty"`
		CreatedAt *internal.DateTime `json:"created_at,omitempty"`
	}{
		embed:     embed(*q),
		Birthdate: internal.NewOptionalDate(q.Birthdate),
		StartDate: internal.NewOptionalDate(q.StartDate),
		UpdatedAt: internal.NewOptionalDateTime(q.UpdatedAt),
		CreatedAt: internal.NewOptionalDateTime(q.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (q *QuoteResponse) String() string {
	if q == nil {
		return "<nil>"
	}
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}

var (
	quoteResponseDriversItemFieldOwnerID           = big.NewInt(1 << 0)
	quoteResponseDriversItemFieldBirthdate         = big.NewInt(1 << 1)
	quoteResponseDriversItemFieldDrivingPercentage = big.NewInt(1 << 2)
)

type QuoteResponseDriversItem struct {
	// Driver's national ID (10 digits starting with 1, 2, or 7)
	OwnerID *string `json:"owner_id,omitempty" url:"owner_id,omitempty"`
	// Driver's birthdate in YYYY-MM-DD format
	Birthdate *time.Time `json:"birthdate,omitempty" url:"birthdate,omitempty" format:"date"`
	// Percentage of driving for this driver (25, 50, 75, or 100)
	DrivingPercentage *int `json:"driving_percentage,omitempty" url:"driving_percentage,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (q *QuoteResponseDriversItem) GetOwnerID() *string {
	if q == nil {
		return nil
	}
	return q.OwnerID
}

func (q *QuoteResponseDriversItem) GetBirthdate() *time.Time {
	if q == nil {
		return nil
	}
	return q.Birthdate
}

func (q *QuoteResponseDriversItem) GetDrivingPercentage() *int {
	if q == nil {
		return nil
	}
	return q.DrivingPercentage
}

func (q *QuoteResponseDriversItem) GetExtraProperties() map[string]interface{} {
	if q == nil {
		return nil
	}
	return q.extraProperties
}

func (q *QuoteResponseDriversItem) require(field *big.Int) {
	if q.explicitFields == nil {
		q.explicitFields = big.NewInt(0)
	}
	q.explicitFields.Or(q.explicitFields, field)
}

// SetOwnerID sets the OwnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponseDriversItem) SetOwnerID(ownerID *string) {
	q.OwnerID = ownerID
	q.require(quoteResponseDriversItemFieldOwnerID)
}

// SetBirthdate sets the Birthdate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponseDriversItem) SetBirthdate(birthdate *time.Time) {
	q.Birthdate = birthdate
	q.require(quoteResponseDriversItemFieldBirthdate)
}

// SetDrivingPercentage sets the DrivingPercentage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponseDriversItem) SetDrivingPercentage(drivingPercentage *int) {
	q.DrivingPercentage = drivingPercentage
	q.require(quoteResponseDriversItemFieldDrivingPercentage)
}

func (q *QuoteResponseDriversItem) UnmarshalJSON(data []byte) error {
	type embed QuoteResponseDriversItem
	var unmarshaler = struct {
		embed
		Birthdate *internal.Date `json:"birthdate,omitempty"`
	}{
		embed: embed(*q),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*q = QuoteResponseDriversItem(unmarshaler.embed)
	q.Birthdate = unmarshaler.Birthdate.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.extraProperties = extraProperties
	q.rawJSON = json.RawMessage(data)
	return nil
}

func (q *QuoteResponseDriversItem) MarshalJSON() ([]byte, error) {
	type embed QuoteResponseDriversItem
	var marshaler = struct {
		embed
		Birthdate *internal.Date `json:"birthdate,omitempty"`
	}{
		embed:     embed(*q),
		Birthdate: internal.NewOptionalDate(q.Birthdate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (q *QuoteResponseDriversItem) String() string {
	if q == nil {
		return "<nil>"
	}
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}

var (
	quoteResponseQuotesItemFieldCompanyName            = big.NewInt(1 << 0)
	quoteResponseQuotesItemFieldCompanyNameAr          = big.NewInt(1 << 1)
	quoteResponseQuotesItemFieldType                   = big.NewInt(1 << 2)
	quoteResponseQuotesItemFieldInsuranceTypeDisplay   = big.NewInt(1 << 3)
	quoteResponseQuotesItemFieldInsuranceTypeDisplayAr = big.NewInt(1 << 4)
	quoteResponseQuotesItemFieldCompanyLogoURL         = big.NewInt(1 << 5)
	quoteResponseQuotesItemFieldSquareCompanyLogoURL   = big.NewInt(1 << 6)
	quoteResponseQuotesItemFieldPrices                 = big.NewInt(1 << 7)
	quoteResponseQuotesItemFieldBenefits               = big.NewInt(1 << 8)
)

type QuoteResponseQuotesItem struct {
	CompanyName *string `json:"company_name,omitempty" url:"company_name,omitempty"`
	// Arabic name of the insurance company. Use this field instead of `company_name` when rendering Arabic UIs.
	CompanyNameAr *string `json:"company_name_ar,omitempty" url:"company_name_ar,omitempty"`
	// Normalised insurance category used to group and filter quotes. Always one of `TPL`, `TPL +`, or `Comprehensive`.
	Type *QuoteResponseQuotesItemType `json:"type,omitempty" url:"type,omitempty"`
	// The insurance type label exactly as the insurance provider intends it to be displayed. While `type` normalises all non-TPL / non-Comprehensive values into `TPL +`, this field preserves the original provider string (e.g. "TPL Plus", "Third Party Plus") and should be shown in the UI wherever the provider's own wording is preferred.
	InsuranceTypeDisplay *string `json:"insurance_type_display,omitempty" url:"insurance_type_display,omitempty"`
	// Arabic translation of `insurance_type_display`. Use this field for Arabic UIs. Falls back to the English value for provider-specific types that do not have a translation.
	InsuranceTypeDisplayAr *string `json:"insurance_type_display_ar,omitempty" url:"insurance_type_display_ar,omitempty"`
	// CDN URL for the insurance company's logo.
	CompanyLogoURL *string `json:"company_logo_url,omitempty" url:"company_logo_url,omitempty"`
	// CDN URL for the insurance company's square logo.
	SquareCompanyLogoURL *string `json:"square_company_logo_url,omitempty" url:"square_company_logo_url,omitempty"`
	// An array representing each price. This will have the premium and the deductible
	Prices []*QuotePrice `json:"prices,omitempty" url:"prices,omitempty"`
	// An array representing the different benefits offered by the company. Some of them are free and comes with the insurance, some are paid and optional
	Benefits []*Benefit `json:"benefits,omitempty" url:"benefits,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (q *QuoteResponseQuotesItem) GetCompanyName() *string {
	if q == nil {
		return nil
	}
	return q.CompanyName
}

func (q *QuoteResponseQuotesItem) GetCompanyNameAr() *string {
	if q == nil {
		return nil
	}
	return q.CompanyNameAr
}

func (q *QuoteResponseQuotesItem) GetType() *QuoteResponseQuotesItemType {
	if q == nil {
		return nil
	}
	return q.Type
}

func (q *QuoteResponseQuotesItem) GetInsuranceTypeDisplay() *string {
	if q == nil {
		return nil
	}
	return q.InsuranceTypeDisplay
}

func (q *QuoteResponseQuotesItem) GetInsuranceTypeDisplayAr() *string {
	if q == nil {
		return nil
	}
	return q.InsuranceTypeDisplayAr
}

func (q *QuoteResponseQuotesItem) GetCompanyLogoURL() *string {
	if q == nil {
		return nil
	}
	return q.CompanyLogoURL
}

func (q *QuoteResponseQuotesItem) GetSquareCompanyLogoURL() *string {
	if q == nil {
		return nil
	}
	return q.SquareCompanyLogoURL
}

func (q *QuoteResponseQuotesItem) GetPrices() []*QuotePrice {
	if q == nil {
		return nil
	}
	return q.Prices
}

func (q *QuoteResponseQuotesItem) GetBenefits() []*Benefit {
	if q == nil {
		return nil
	}
	return q.Benefits
}

func (q *QuoteResponseQuotesItem) GetExtraProperties() map[string]interface{} {
	if q == nil {
		return nil
	}
	return q.extraProperties
}

func (q *QuoteResponseQuotesItem) require(field *big.Int) {
	if q.explicitFields == nil {
		q.explicitFields = big.NewInt(0)
	}
	q.explicitFields.Or(q.explicitFields, field)
}

// SetCompanyName sets the CompanyName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponseQuotesItem) SetCompanyName(companyName *string) {
	q.CompanyName = companyName
	q.require(quoteResponseQuotesItemFieldCompanyName)
}

// SetCompanyNameAr sets the CompanyNameAr field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponseQuotesItem) SetCompanyNameAr(companyNameAr *string) {
	q.CompanyNameAr = companyNameAr
	q.require(quoteResponseQuotesItemFieldCompanyNameAr)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponseQuotesItem) SetType(type_ *QuoteResponseQuotesItemType) {
	q.Type = type_
	q.require(quoteResponseQuotesItemFieldType)
}

// SetInsuranceTypeDisplay sets the InsuranceTypeDisplay field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponseQuotesItem) SetInsuranceTypeDisplay(insuranceTypeDisplay *string) {
	q.InsuranceTypeDisplay = insuranceTypeDisplay
	q.require(quoteResponseQuotesItemFieldInsuranceTypeDisplay)
}

// SetInsuranceTypeDisplayAr sets the InsuranceTypeDisplayAr field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponseQuotesItem) SetInsuranceTypeDisplayAr(insuranceTypeDisplayAr *string) {
	q.InsuranceTypeDisplayAr = insuranceTypeDisplayAr
	q.require(quoteResponseQuotesItemFieldInsuranceTypeDisplayAr)
}

// SetCompanyLogoURL sets the CompanyLogoURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponseQuotesItem) SetCompanyLogoURL(companyLogoURL *string) {
	q.CompanyLogoURL = companyLogoURL
	q.require(quoteResponseQuotesItemFieldCompanyLogoURL)
}

// SetSquareCompanyLogoURL sets the SquareCompanyLogoURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponseQuotesItem) SetSquareCompanyLogoURL(squareCompanyLogoURL *string) {
	q.SquareCompanyLogoURL = squareCompanyLogoURL
	q.require(quoteResponseQuotesItemFieldSquareCompanyLogoURL)
}

// SetPrices sets the Prices field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponseQuotesItem) SetPrices(prices []*QuotePrice) {
	q.Prices = prices
	q.require(quoteResponseQuotesItemFieldPrices)
}

// SetBenefits sets the Benefits field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (q *QuoteResponseQuotesItem) SetBenefits(benefits []*Benefit) {
	q.Benefits = benefits
	q.require(quoteResponseQuotesItemFieldBenefits)
}

func (q *QuoteResponseQuotesItem) UnmarshalJSON(data []byte) error {
	type unmarshaler QuoteResponseQuotesItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*q = QuoteResponseQuotesItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *q)
	if err != nil {
		return err
	}
	q.extraProperties = extraProperties
	q.rawJSON = json.RawMessage(data)
	return nil
}

func (q *QuoteResponseQuotesItem) MarshalJSON() ([]byte, error) {
	type embed QuoteResponseQuotesItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*q),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, q.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (q *QuoteResponseQuotesItem) String() string {
	if q == nil {
		return "<nil>"
	}
	if len(q.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(q.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(q); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", q)
}

// Normalised insurance category used to group and filter quotes. Always one of `TPL`, `TPL +`, or `Comprehensive`.
type QuoteResponseQuotesItemType string

const (
	QuoteResponseQuotesItemTypeTpl           QuoteResponseQuotesItemType = "TPL"
	QuoteResponseQuotesItemTypeComprehensive QuoteResponseQuotesItemType = "Comprehensive"
)

func NewQuoteResponseQuotesItemTypeFromString(s string) (QuoteResponseQuotesItemType, error) {
	switch s {
	case "TPL":
		return QuoteResponseQuotesItemTypeTpl, nil
	case "Comprehensive":
		return QuoteResponseQuotesItemTypeComprehensive, nil
	}
	var t QuoteResponseQuotesItemType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (q QuoteResponseQuotesItemType) Ptr() *QuoteResponseQuotesItemType {
	return &q
}

var (
	deleteQuoteRequestsIDResponseFieldMessage = big.NewInt(1 << 0)
)

type DeleteQuoteRequestsIDResponse struct {
	Message *string `json:"message,omitempty" url:"message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteQuoteRequestsIDResponse) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}

func (d *DeleteQuoteRequestsIDResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeleteQuoteRequestsIDResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteQuoteRequestsIDResponse) SetMessage(message *string) {
	d.Message = message
	d.require(deleteQuoteRequestsIDResponseFieldMessage)
}

func (d *DeleteQuoteRequestsIDResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteQuoteRequestsIDResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteQuoteRequestsIDResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteQuoteRequestsIDResponse) MarshalJSON() ([]byte, error) {
	type embed DeleteQuoteRequestsIDResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteQuoteRequestsIDResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type PostQuoteRequestsRequestAcceptLanguage string

const (
	PostQuoteRequestsRequestAcceptLanguageAr PostQuoteRequestsRequestAcceptLanguage = "ar"
)

func NewPostQuoteRequestsRequestAcceptLanguageFromString(s string) (PostQuoteRequestsRequestAcceptLanguage, error) {
	switch s {
	case "ar":
		return PostQuoteRequestsRequestAcceptLanguageAr, nil
	}
	var t PostQuoteRequestsRequestAcceptLanguage
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PostQuoteRequestsRequestAcceptLanguage) Ptr() *PostQuoteRequestsRequestAcceptLanguage {
	return &p
}

var (
	postQuoteRequestsRequestDriversItemFieldOwnerID           = big.NewInt(1 << 0)
	postQuoteRequestsRequestDriversItemFieldBirthdate         = big.NewInt(1 << 1)
	postQuoteRequestsRequestDriversItemFieldDrivingPercentage = big.NewInt(1 << 2)
)

type PostQuoteRequestsRequestDriversItem struct {
	// Driver's national ID. Must be 10 digits starting with 1, 2, or 7.
	OwnerID string `json:"owner_id" url:"owner_id"`
	// Driver's birthdate in YYYY-MM-DD format.
	Birthdate time.Time `json:"birthdate" url:"birthdate" format:"date"`
	// Percentage of driving for this driver. Valid values are 25, 50, 75, or 100. The sum of all drivers' percentages must equal 100.
	DrivingPercentage int `json:"driving_percentage" url:"driving_percentage"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PostQuoteRequestsRequestDriversItem) GetOwnerID() string {
	if p == nil {
		return ""
	}
	return p.OwnerID
}

func (p *PostQuoteRequestsRequestDriversItem) GetBirthdate() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.Birthdate
}

func (p *PostQuoteRequestsRequestDriversItem) GetDrivingPercentage() int {
	if p == nil {
		return 0
	}
	return p.DrivingPercentage
}

func (p *PostQuoteRequestsRequestDriversItem) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PostQuoteRequestsRequestDriversItem) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetOwnerID sets the OwnerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequestDriversItem) SetOwnerID(ownerID string) {
	p.OwnerID = ownerID
	p.require(postQuoteRequestsRequestDriversItemFieldOwnerID)
}

// SetBirthdate sets the Birthdate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequestDriversItem) SetBirthdate(birthdate time.Time) {
	p.Birthdate = birthdate
	p.require(postQuoteRequestsRequestDriversItemFieldBirthdate)
}

// SetDrivingPercentage sets the DrivingPercentage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostQuoteRequestsRequestDriversItem) SetDrivingPercentage(drivingPercentage int) {
	p.DrivingPercentage = drivingPercentage
	p.require(postQuoteRequestsRequestDriversItemFieldDrivingPercentage)
}

func (p *PostQuoteRequestsRequestDriversItem) UnmarshalJSON(data []byte) error {
	type embed PostQuoteRequestsRequestDriversItem
	var unmarshaler = struct {
		embed
		Birthdate *internal.Date `json:"birthdate"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = PostQuoteRequestsRequestDriversItem(unmarshaler.embed)
	p.Birthdate = unmarshaler.Birthdate.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PostQuoteRequestsRequestDriversItem) MarshalJSON() ([]byte, error) {
	type embed PostQuoteRequestsRequestDriversItem
	var marshaler = struct {
		embed
		Birthdate *internal.Date `json:"birthdate"`
	}{
		embed:     embed(*p),
		Birthdate: internal.NewDate(p.Birthdate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PostQuoteRequestsRequestDriversItem) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
