// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "sdk/internal"
)

var (
	badRequestErrorBodyFieldCode    = big.NewInt(1 << 0)
	badRequestErrorBodyFieldMessage = big.NewInt(1 << 1)
)

type BadRequestErrorBody struct {
	Code    *string `json:"code,omitempty" url:"code,omitempty"`
	Message *string `json:"message,omitempty" url:"message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BadRequestErrorBody) GetCode() *string {
	if b == nil {
		return nil
	}
	return b.Code
}

func (b *BadRequestErrorBody) GetMessage() *string {
	if b == nil {
		return nil
	}
	return b.Message
}

func (b *BadRequestErrorBody) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BadRequestErrorBody) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BadRequestErrorBody) SetCode(code *string) {
	b.Code = code
	b.require(badRequestErrorBodyFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BadRequestErrorBody) SetMessage(message *string) {
	b.Message = message
	b.require(badRequestErrorBodyFieldMessage)
}

func (b *BadRequestErrorBody) UnmarshalJSON(data []byte) error {
	type unmarshaler BadRequestErrorBody
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BadRequestErrorBody(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BadRequestErrorBody) MarshalJSON() ([]byte, error) {
	type embed BadRequestErrorBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BadRequestErrorBody) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	companyQuoteFieldCompanyName = big.NewInt(1 << 0)
	companyQuoteFieldPrices      = big.NewInt(1 << 1)
	companyQuoteFieldBenefits    = big.NewInt(1 << 2)
)

type CompanyQuote struct {
	CompanyName *string       `json:"company_name,omitempty" url:"company_name,omitempty"`
	Prices      []*QuotePrice `json:"prices,omitempty" url:"prices,omitempty"`
	Benefits    []*Benefit    `json:"benefits,omitempty" url:"benefits,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CompanyQuote) GetCompanyName() *string {
	if c == nil {
		return nil
	}
	return c.CompanyName
}

func (c *CompanyQuote) GetPrices() []*QuotePrice {
	if c == nil {
		return nil
	}
	return c.Prices
}

func (c *CompanyQuote) GetBenefits() []*Benefit {
	if c == nil {
		return nil
	}
	return c.Benefits
}

func (c *CompanyQuote) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CompanyQuote) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetCompanyName sets the CompanyName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CompanyQuote) SetCompanyName(companyName *string) {
	c.CompanyName = companyName
	c.require(companyQuoteFieldCompanyName)
}

// SetPrices sets the Prices field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CompanyQuote) SetPrices(prices []*QuotePrice) {
	c.Prices = prices
	c.require(companyQuoteFieldPrices)
}

// SetBenefits sets the Benefits field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CompanyQuote) SetBenefits(benefits []*Benefit) {
	c.Benefits = benefits
	c.require(companyQuoteFieldBenefits)
}

func (c *CompanyQuote) UnmarshalJSON(data []byte) error {
	type unmarshaler CompanyQuote
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CompanyQuote(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CompanyQuote) MarshalJSON() ([]byte, error) {
	type embed CompanyQuote
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CompanyQuote) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	errorFieldCode    = big.NewInt(1 << 0)
	errorFieldMessage = big.NewInt(1 << 1)
)

type Error struct {
	Code    *string `json:"code,omitempty" url:"code,omitempty"`
	Message *string `json:"message,omitempty" url:"message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *Error) GetCode() *string {
	if e == nil {
		return nil
	}
	return e.Code
}

func (e *Error) GetMessage() *string {
	if e == nil {
		return nil
	}
	return e.Message
}

func (e *Error) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *Error) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *Error) SetCode(code *string) {
	e.Code = code
	e.require(errorFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *Error) SetMessage(message *string) {
	e.Message = message
	e.require(errorFieldMessage)
}

func (e *Error) UnmarshalJSON(data []byte) error {
	type unmarshaler Error
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = Error(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *Error) MarshalJSON() ([]byte, error) {
	type embed Error
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *Error) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	unauthorizedErrorBodyFieldCode    = big.NewInt(1 << 0)
	unauthorizedErrorBodyFieldMessage = big.NewInt(1 << 1)
)

type UnauthorizedErrorBody struct {
	Code    *string `json:"code,omitempty" url:"code,omitempty"`
	Message *string `json:"message,omitempty" url:"message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UnauthorizedErrorBody) GetCode() *string {
	if u == nil {
		return nil
	}
	return u.Code
}

func (u *UnauthorizedErrorBody) GetMessage() *string {
	if u == nil {
		return nil
	}
	return u.Message
}

func (u *UnauthorizedErrorBody) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UnauthorizedErrorBody) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnauthorizedErrorBody) SetCode(code *string) {
	u.Code = code
	u.require(unauthorizedErrorBodyFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnauthorizedErrorBody) SetMessage(message *string) {
	u.Message = message
	u.require(unauthorizedErrorBodyFieldMessage)
}

func (u *UnauthorizedErrorBody) UnmarshalJSON(data []byte) error {
	type unmarshaler UnauthorizedErrorBody
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UnauthorizedErrorBody(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UnauthorizedErrorBody) MarshalJSON() ([]byte, error) {
	type embed UnauthorizedErrorBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UnauthorizedErrorBody) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}
