// Code generated by Fern. DO NOT EDIT.

package quotes

import (
	context "context"

	motorgosdk "github.com/YasminaAI/motor-go-sdk"
	core "github.com/YasminaAI/motor-go-sdk/core"
	internal "github.com/YasminaAI/motor-go-sdk/internal"
	option "github.com/YasminaAI/motor-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (c *Client) ShowQuote(
	ctx context.Context,
	request *motorgosdk.GetQuoteRequestsIDRequest,
	opts ...option.RequestOption,
) (*motorgosdk.QuoteResponse, error) {
	response, err := c.WithRawResponse.ShowQuote(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DeleteQuote(
	ctx context.Context,
	request *motorgosdk.DeleteQuoteRequestsIDRequest,
	opts ...option.RequestOption,
) (*motorgosdk.DeleteQuoteRequestsIDResponse, error) {
	response, err := c.WithRawResponse.DeleteQuote(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ListQuotes(
	ctx context.Context,
	request *motorgosdk.GetQuoteRequestsRequest,
	opts ...option.RequestOption,
) (*motorgosdk.PaginatedQuoteResponse, error) {
	response, err := c.WithRawResponse.ListQuotes(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// For getting prices with benefits.
// The Quote IDs can be used later to issue a policy
func (c *Client) RequestQuotes(
	ctx context.Context,
	request *motorgosdk.PostQuoteRequestsRequest,
	opts ...option.RequestOption,
) (*motorgosdk.QuoteResponse, error) {
	response, err := c.WithRawResponse.RequestQuotes(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
