// Code generated by Fern. DO NOT EDIT.

package otps

import (
	context "context"
	sdk "sdk"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// This endpoint sends a one-time password (OTP) to the provided email and phone number for quote verification. It should be called before creating a quote request.
func (c *Client) RequestOtpForQuoteVerification(
	ctx context.Context,
	request *sdk.PostQuoteOtpRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.RequestOtpForQuoteVerification(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// This endpoint sends a one-time password (OTP). It should be called before issuing a policy.
func (c *Client) RequestOtpForIssuingPolicy(
	ctx context.Context,
	request *sdk.PostIssueOtpRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.RequestOtpForIssuingPolicy(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
