// Code generated by Fern. DO NOT EDIT.

package policies

import (
	context "context"

	motorgosdk "github.com/YasminaAI/motor-go-sdk"
	core "github.com/YasminaAI/motor-go-sdk/core"
	internal "github.com/YasminaAI/motor-go-sdk/internal"
	option "github.com/YasminaAI/motor-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Show a specific policy
func (c *Client) ShowPolicy(
	ctx context.Context,
	request *motorgosdk.GetPoliciesCarPolicyRequest,
	opts ...option.RequestOption,
) (*motorgosdk.Policy, error) {
	response, err := c.WithRawResponse.ShowPolicy(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Listing requested policies
func (c *Client) ListPolicies(
	ctx context.Context,
	request *motorgosdk.GetPoliciesRequest,
	opts ...option.RequestOption,
) (*motorgosdk.PaginatedPolicyResponse, error) {
	response, err := c.WithRawResponse.ListPolicies(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// For issuing a new policy
func (c *Client) IssuePolicy(
	ctx context.Context,
	request *motorgosdk.PostPoliciesRequest,
	opts ...option.RequestOption,
) (*motorgosdk.Policy, error) {
	response, err := c.WithRawResponse.IssuePolicy(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
